### ISSUE TITLE
Usage/Help message is not provdied

### ISSUE THREAD

**Issue by bahramis** [Xinglab/rmats2sashimiplot#1]
When program is run with no parameters (or with the help parameter), it should output a complete usage message to explain what the parameters are and print the current message as examples at the end.

**Comment by tingtseng** [comment]
The issue has been fixed.

**Comment by bahramis** [comment]
There also should be a "-h" parameter for help. The same usage message should be displayed as if the program is run with no parameters.

**Comment by tingtseng** [comment]
added -h parameter and also -help
