### ISSUE TITLE
Install the master version of rmats2sashimiplot by conda

### ISSUE THREAD

**Issue by bioPG** [Xinglab/rmats2sashimiplot#104]
Hi, I noticed that Conda only has version 2.0.4 of rmats2sashimiplot available for installation, but it has some minor issues. I saw that these issues have been resolved in the master version. Could you please consider releasing a new version of rmats2sashimiplot on Conda?

**Comment by EricKutschera** [comment]
rmats2sashimiplot v3.0.0 is now available on conda: https://anaconda.org/bioconda/rmats2sashimiplot/files?version=3.0.0
