### ISSUE TITLE
WDL script for rmats2sashimiplot

### ISSUE THREAD

**Issue by JingAnyaSun** [Xinglab/rmats2sashimiplot#108]
Hi rMATS team,

Thanks for creating the amazing software, which is very useful! I was wondering if you have the wdl script for rmats2sashimiplot for cloud computing users. If so, that'd be great. 

Best,
Jing

**Comment by EricKutschera** [comment]
I have a wdl script in this pull request: https://github.com/Xinglab/rmats2sashimiplot/pull/109/files

Let me know if you have any issues with that wdl

**Comment by JingAnyaSun** [comment]
Hi Eric,

Thanks for your kind reply which is super helpful! I have tested it on Terra and it worked perfectly:)

Best,
Jing
