### ISSUE TITLE
rmats2sashimiplot IndexError

### ISSUE THREAD

**Issue by bluesea2017** [Xinglab/rmats2sashimiplot#11]
Hello,
 When I run rmats2sashimiplot, it had this probem as follows, how can I settle this problem?
  x = [graphcoords[s], graphcoords[e], graphcoords[e], graphcoords[s]]
   IndexError: index 5341 is out of bounds for axis 0 with size 5126
Thank you!

**Comment by dm-druid** [comment]
Could you please give more details about your situation? If possible,  you can share your data and the parameters with us, then we can try to find the problem.

**Comment by ShiehShieh** [comment]
Could you show us more info? For example, your rMATS_Output, command line options for running rmats2sashimiplot, and sashimi plots.

**Comment by ShiehShieh** [comment]
As @dm-druid  said, could you please show us more info? For example, your rMATS_Output, command line options for running rmats2sashimiplot, and sashimi plots.

**Comment by bluesea2017** [comment]
rmats2sashimiplot-2.0.0-py2.7.egg/MISO/misopy/sashimi_plot/plot_utils/plot_gene.py", line 604, in plot_mRNAs
    x = [graphcoords[s], graphcoords[e], graphcoords[e], graphcoords[s]]
   IndexError: index 5341 is out of bounds for axis 0 with size 5126
    
    Run parameter:
    /rmats2sashimiplot --       b1  SAMPLE_1/REP_1/aligned.sorted.bam, SAMPLE_1/REP_2/aligned.sorted.bam  --b2  SAMPLE_2/REP_1/aligned.sorted.bam   -e  A3SS.txt  --l1 D4 --l2 B2 --exon_s 1 --intron_s 5 -o plot -t A3SS

    Down load this software  data:20170511  ,the newest version.
rMATS out:29996	"ENSMUSG00000071068.6"	"Treml2"	chr17	+	48307479	48308273	48308056	48308273	48302611	48302932	29996	493,476	111,86	1522	57	278	139	0.0	0.0	0.69,0.735	0.93	-0.218

**Comment by EricKutschera** [comment]
Closing since there has been no update. Please open a new issue if needed after trying the latest source code
