### ISSUE TITLE
problem in using grouping option and coordinates?

### ISSUE THREAD

**Issue by edonato28** [Xinglab/rmats2sashimiplot#121]
Hi all, I am using rmats2sashimiplot and I noticed that when running the grouping option together with coordinates, in the final plot are shown the first elements of the two groups rather than the average. Is grouping only working when events are provided?
Thanks in advance.

**Comment by EricKutschera** [comment]
I tried these commands with the test data from the README and the plots seemed ok. I used rmats2sashimiplot v3.0.0 installed from bioconda. I used grouping.gf:
```
group1name: 1-2
group2name: 3-6
```

grouped using event:
```
rmats2sashimiplot --b1 ./rmats2sashimiplot_test_data/sample_1_replicate_1.bam,./rmats2sashimiplot_test_data/sample_1_replicate_2.bam,./rmats2sashimiplot_test_data/sample_1_replicate_3.bam --b2 ./rmats2sashimiplot_test_data/sample_2_replicate_1.bam,./rmats2sashimiplot_test_data/sample_2_replicate_2.bam,./rmats2sashimiplot_test_data/sample_2_replicate_3.bam --event-type SE -e ./rmats2sashimiplot_test_data/SE.MATS.JC.txt --l1 SampleOne --l2 SampleTwo --exon_s 1 --intron_s 5 -o test_grouped_output --group-info grouping.gf
```

coordinates:
```
rmats2sashimiplot --b1 ./rmats2sashimiplot_test_data/sample_1_replicate_1.bam,./rmats2sashimiplot_test_data/sample_1_replicate_2.bam,./rmats2sashimiplot_test_data/sample_1_replicate_3.bam --b2 ./rmats2sashimiplot_test_data/sample_2_replicate_1.bam,./rmats2sashimiplot_test_data/sample_2_replicate_2.bam,./rmats2sashimiplot_test_data/sample_2_replicate_3.bam -c chr16:+:9000:25000:./rmats2sashimiplot_test_data/annotation.gff3 --l1 SampleOne --l2 SampleTwo --exon_s 1 --intron_s 5 -o test_coordinate_output
```

grouped using coordinates:
```
rmats2sashimiplot --b1 ./rmats2sashimiplot_test_data/sample_1_replicate_1.bam,./rmats2sashimiplot_test_data/sample_1_replicate_2.bam,./rmats2sashimiplot_test_data/sample_1_replicate_3.bam --b2 ./rmats2sashimiplot_test_data/sample_2_replicate_1.bam,./rmats2sashimiplot_test_data/sample_2_replicate_2.bam,./rmats2sashimiplot_test_data/sample_2_replicate_3.bam -c chr16:+:9000:25000:./rmats2sashimiplot_test_data/annotation.gff3 --l1 SampleOne --l2 SampleTwo --exon_s 1 --intron_s 5 -o test_grouped_coord_out --group-info grouping.gf
```

**Comment by edonato28** [comment]
Thanks for checking...then what I was receiving was indeed the average of the samples in each group and I was erroneously thinking that only 2 samples were picked. What I have as results is in contrast with boxplot using normalized counts from RNAseq and RTqPCR data. 

I am using bam files obtained after adapter trimming and alignment using STAR with the following parameters

alignIntronMax: 500.000, alignMatesGapMax: 500.000, outSAMunmapped: Within, outFilterMultimapNmax: 1, outFilterMismatchNmax: 3, outFilterMismatchNoverLmax: 0.3, sjdbOverhang: 50, chimSegmentMin: 15,
chimScoreMin: 1, chimScoreJunctionNonGTAG: 0, chimJunctionOverhangMin: 15

Am I using the wrong input files? Should I process differently the samples and redo the alignment?
Thanks

**Comment by EricKutschera** [comment]
Those STAR parameters seem fine to me. Here's the STAR command used in rMATS for comparison: https://github.com/Xinglab/rmats-turbo/blob/v4.2.0/rmats.py#L66

Can you upload the bam files and provide the rmats2sashimiplot command you're using? Or can you reproduce similar behavior from rmats2sashimiplot on a public dataset?

**Comment by edonato28** [comment]
I figured out the problem: it was a typo in my grouping.gf file.
Thanks a lot for the help and sorry for the trouble :)
