### ISSUE TITLE
rmats2sashimiplot didn't create the PDF file with the plot

### ISSUE THREAD

**Issue by mlcsmits** [Xinglab/rmats2sashimiplot#123]
Hey, rmats2sashimiplot Team, I was working on Ubuntu via mobaXterm and trying to run rmats2sashimiplot 3.0.0 when it exited in failure. Here is everything that I know: I ran the following command: python3 /mnt/studentfiles/2024/2024MBI03/rmats2sashimiplot-3.0.0/src/rmats2sashimiplot/rmats2sashimiplot.py --b1 /mnt/studentfiles/2024/2024MBI03/subset/sorted_SRR19760417.bam -c NW_001886736.1:+:92100:92714:/mnt/studentfiles/2024/2024MBI03/RefSeq/genomic2.gff3  --event-type SE -e /mnt/studentfiles/2024/2024MBI03/rmats/SE.MATS.JC.txt --l1 SRR417 -o plot-output417 . This is the output of the tool: 
![image](https://github.com/Xinglab/rmats2sashimiplot/assets/161313142/dc5e1090-5d67-4261-b4d4-573053e8ca8e)

I have read it, but I need help understanding why it doesn't make a PDF file. I've read the manual page for this tool, and I'm calling it correctly; I attempted calling all the event types, but it did not succeed. I personally think that rMATS could not find any events because this is the output summary file:
![image](https://github.com/Xinglab/rmats2sashimiplot/assets/161313142/379ee899-7786-46dc-ab2e-bf231b2939c7)

Could you please help me?

**Comment by EricKutschera** [comment]
The commands included `-e /path/to/SE.MATS.JC.txt`. With that option rmats2sashimiplot will make plots for the events in that file. The summary file shows that no events were detected. If the `-e` file is empty then there is nothing for rmats2sashimiplot to show. You could try using `-c` instead of `-e` to tell rmats2sashimiplot to make a plot for a particular coordinate range

Here are some posts that might help with rMATS giving empty event files:
https://github.com/Xinglab/rmats-turbo/issues/95
https://github.com/Xinglab/rmats-turbo/issues/154

**Comment by mlcsmits** [comment]
Hi, EricKutschera. Thanks for your quick response. I now use the command 
python3 /mnt/studentfiles/2024/2024MBI03/rmats2sashimiplot-3.0.0/src/rmats2sashimiplot/rmats2sashimiplot.py --b1 /mnt/studentfiles/2024/2024MBI03/subset/sorted_SRR19760417.bam -c NW_001886736.1:+:92100:92714:/mnt/studentfiles/2024/2024MBI03/RefSeq/genomic2.gff3  --event-type SE --l1 SRR417 -o plot-output417

It results in the following error:
![image](https://github.com/Xinglab/rmats2sashimiplot/assets/161313142/c065c3ed-531b-4e58-bb93-472c373c4e14)

It creates these files:
![image](https://github.com/Xinglab/rmats2sashimiplot/assets/161313142/abd355a7-2f49-4ed8-bd30-fd41e4823940)

Even when I try to give the command without the --event-type flag, it results in these files.

What could I have done wrong?
I also want to try multiple regions, so multiple NW_... numbers. Is that possible for rmats2sashimiplot?

**Comment by mlcsmits** [comment]
Hey Eric Kutschera, I have tried this command on data that has alternative splicing according to rMATS:
python3 /mnt/studentfiles/2024/2024MBI03/rmats2sashimiplot-3.0.0/src/rmats2sashimiplot/rmats2sashimiplot.py --b1 /mnt/studentfiles/2024/2024MBI03/b2.txt -c /mnt/studentfiles/2024/2024MBI03/RefSeq/genomic2.gff3  --event-type SE -e /mnt/studentfiles/2024/2024MBI03/rmats3/SE.MATS.JC.txt --l1 SRR417 -o plot-output417_3

I got a long error message repeating the same error.:
![image](https://github.com/Xinglab/rmats2sashimiplot/assets/161313142/251fbeec-558f-4e49-af55-d7bb36e1affb)
![image](https://github.com/Xinglab/rmats2sashimiplot/assets/161313142/06362706-23d5-46d1-9db1-39f70c6fda3e)
![image](https://github.com/Xinglab/rmats2sashimiplot/assets/161313142/0a3e736c-c0fc-4b2b-863b-7a839338f794)

I don't know if I do something wrong, could you please help me?
