### ISSUE TITLE
RPKM values as output instead of the sashimiplot pdf

### ISSUE THREAD

**Issue by mlcsmits** [Xinglab/rmats2sashimiplot#126]
Hi @EricKutschera, I was wondering where I can find the data points from the sashimi plot because I would like to compare the RPKM values from the two groups I have made on a very small scale. I thought the .pickle file contained the data points, but it is not human-readable; I have tried to make it readable with pickle.load(), but then the file is way too big.

Do you have any suggestions to solve this problem?

**Comment by EricKutschera** [comment]
The values are ready at this line:
https://github.com/Xinglab/rmats2sashimiplot/blob/v3.0.0/src/MISO/misopy/sashimi_plot/plot_utils/plot_gene.py#L101

You could write them to a file with:
```
with open('/path/to/coord_out.txt', 'at') as out_handle:
    out_handle.write('{}\n'.format(bam_group))
    for wiggle_i, wiggle_value in enumerate(wiggle):
        out_handle.write('{},{}\n'.format(wiggle_i + tx_start, wiggle_value))
```

**Comment by EricKutschera** [comment]
The code in this commit writes the coordinates to a  file in the same directory as the plot:
https://github.com/Xinglab/rmats2sashimiplot/commit/97561cb62feeb8b3f73a08e4f4127347c689264c

**Comment by mlcsmits** [comment]
Thank you for your help
