### ISSUE TITLE
Package installation

### ISSUE THREAD

**Issue by Yuqiu-Yang** [Xinglab/rmats2sashimiplot#132]
Thank you so much for developing this wonderful suite of tools. 

I followed the instructions included in your paper: https://www.nature.com/articles/s41596-023-00944-2 and installed rmats2sashimiplot 3.0.0 and rmats 4.1.1. 
However, I found out that in addition to those steps, I also need to install pysam 0.8.4, scipy 1.5.4, and matplotlib 3.3.1. 

Also, it seems that the flag --remove-event-chr-prefix has to be specified. Otherwise, there will be error messages like 

Error retrieving files from chrGL000195.1: invalid reference `chrGL000195.1`
Are you sure chrGL000195.1 appears in your BAM file?

I am wondering if this is the correct way to execute your program?

Thank you very much~

**Comment by EricKutschera** [comment]
The paper does list pysam, scipy, and matplotlib as dependencies of rmats2sashimiplot.  If you install from conda then the dependencies will also be installed: `conda install -c conda-forge -c bioconda rmats2sashimiplot=3.0.0`

`--keep-event-chr-prefix` or `--remove-event-chr-prefix` might be needed depending on the inputs used with rmats2sashimiplot and which contig(s) you are plotting. The code tries to automatically handle most cases, but it may not handle contigs without 'chr' like `GL000195.1` correctly when other contigs do start with 'chr': https://github.com/Xinglab/rmats2sashimiplot/issues/101#issuecomment-1642016386

**Comment by Yuqiu-Yang** [comment]
Thank you very much for your prompt response.
