### ISSUE TITLE
What the mean of lncLevel at the right side of sashimiplot?

### ISSUE THREAD

**Issue by xflicsu** [Xinglab/rmats2sashimiplot#14]
![imag](https://github.com/Xinglab/rmats2sashimiplot/raw/master/img/plotwithevent.png)

What the mean of lncLevel at the right side of sashimiplot?

**Comment by EricKutschera** [comment]
The IncLevel values are from the IncLevel1 and IncLevel2 columns of the rMATS output file: https://github.com/Xinglab/rmats-turbo#output
