### ISSUE TITLE
Colouring of groups does not work

### ISSUE THREAD

**Issue by cmonger** [Xinglab/rmats2sashimiplot#15]
Hi. Thanks for your script, its very useful.

When I have each sample plotted I am able to specify colours E.G:
`rmats2sashimiplot --b1 ../../total-rna-1.sam.sorted.bam,../../total-rna-2.sam.sorted.bam,../../total-rna-3.sam.sorted.bam,../../total-rna-4.sam.sorted.bam --b2 ../../total-rna-5.sam.sorted.bam,../../total-rna-6.sam.sorted.bam,../../total-rna-7.sam.sorted.bam,../../total-rna-8.sam.sorted.bam -t SE -e MATS_SIG/slirp.txt --l1 37C_Rep_ --l2 31C_Rep_ -o plot--intron_s 10 --no-text-background --color '#ee5c42,#ee5c42,#ee5c42,#ee5c42,#00bfff,#00bfff,#00bfff,#00bfff'`

But when I change to using a group file it does not seem to be possible to choose the colours used in the plot E.G: 
`rmats2sashimiplot --b1 ../../total-rna-1.sam.sorted.bam,../../total-rna-2.sam.sorted.bam,../../total-rna-3.sam.sorted.bam,../../total-rna-4.sam.sorted.bam --b2 ../../total-rna-5.sam.sorted.bam,../../total-rna-6.sam.sorted.bam,../../total-rna-7.sam.sorted.bam,../../total-rna-8.sam.sorted.bam -t SE -e MATS_SIG/slirp.txt --l1 37C_Rep_ --l2 31C_Rep_ -o plot--intron_s 10 --no-text-background --color '#ee5c42,#ee5c42,#ee5c42,#ee5c42,#00bfff,#00bfff,#00bfff,#00bfff' --group-info grouping.gf`
Returns a plot with the same colours as found in the tutorial for grouped plots. https://github.com/Xinglab/rmats2sashimiplot/blob/master/README.md

This is an issue because the colours chosen for grouped plotting by default are too dark to see the junction counts when the --no-text-background flag is on.

Is it possible to choose the colours for groups? If not you may want to consider changing the script to have lighter colours.

**Comment by ShiehShieh** [comment]
Hi @cmonger. Thanks for your feedback. You observation is correct. Will fix it and let you know.

**Comment by ShiehShieh** [comment]
Probably fixed now with latest commit. Closing for now. @cmonger
