### ISSUE TITLE
working with Ensembl annotation? 

### ISSUE THREAD

**Issue by silvanopiazza** [Xinglab/rmats2sashimiplot#19]
Dear all,
I am trying to use data with rmats2sashimiplot that it was analyzed through a stardard pipeline with Ensembl annotation:

STAR aligner with Homo_sapiens.GRCh38.dna.primary_assembly.fa and Homo_sapiens.GRCh38.90.gtf
from Ensembl, so:
`> head   Homo_sapiens.GRCh38.90.gtf`
`#!genome-build GRCh38.p10`
`#!genome-version GRCh38`
`#!genome-date 2013-12`
`#!genome-build-accession NCBI:GCA_000001405.25`
`#!genebuild-last-updated 2017-06`
`1       havana  gene    11869   14409   .       +       .       gene_id "ENSG00000223972"; gene_version "5"; gene_name "DDX11L1"; gene_source "havana"; gene_biotype "transcribed_unprocessed_pseudogene";`
`1       havana  transcript      11869   14409   .       +       .       gene_id "ENSG00000223972"; gene_version "5"; transcript_id "E .. etcs`

then standard rMats analysis with the same GTF that produce the output files (SE.MATS.JCEC.txt etc...)

`>head SE.MATS.JCEC.txt`
`ID      GeneID  geneSymbol      chr     strand  exonStart_0base exonEnd upstreamES      upstreamEE      downstreamES    downstreamEE    ID      IJC_SAMPLE_1    SJC_SAMPLE_1    IJC_SAMPLE_2    SJC_SAMPLE_2    IncFormLen      SkipFormLen     PValue  FDR     IncLevel1       IncLevel2       IncLevelDifference`
`
0       "ENSG00000160310"       "PRMT2" **chr21**   +       46636438        46636547        46635166        46635763        46636895
        46636990        0       37,68,54,171    74,33,26,6      21,25   15,14   183     74      0.284535011242  1.0     0.168,0.455,0.456,0.92  0.361,0.419     0.11.
`

As you can see from the rMats output file the chromosome position is expressed as chrXX ant not just XX.
In fact when I run rmats2sashimiplot, an error occur:
` Are you sure chrXX appears in your BAM file `

So I changed the output of rMATS removing the 'chr'. After that rmats2sashimiplot  complains with 
`invalid literal for int() with base 10: '' 
There is an exception in plot_with_eventsfile
` 

my command was
`rmats2sashimiplot --b1 T1.bam --b2 T2t.bam -t SE -e SE.MATS.JCEC.txt  --l1 Tumor --l2 normal -o sashimiplots`

any help, please
thank you all
Silvano
                   -`

**Comment by ShiehShieh** [comment]
Hi Silvano,

Could you please send me the SE.MATS.JCEC.txt file? Probably a few lines.
And also, what rMATS version are you using? Is that rMATS v3.2.5?

Thanks.
Zhijie Xie

**Comment by silvanopiazza** [comment]
dear Zhijie,
I am using the lateset  rMATS docker version (should be based on regular version v3.2.5).
For the email, could you tell me which address should I have to use, please?
thanks,
Silvano

**Comment by apastore** [comment]
There is any update on this? I am having the exact same issues. With both GRCH37 and GRCh38. And the last rMATS version. 
Thanks a lot!

**Comment by Ekomshiro** [comment]
Bump.
Same here with hg37 and latest plot from git, using tag
-c chr#:+:start:end:gff3

**Comment by EricKutschera** [comment]
The "Are you sure chrXX appears in your BAM file" issue was addressed in https://github.com/Xinglab/rmats2sashimiplot/pull/36

Please open a new issue if needed after trying the latest source code
