### ISSUE TITLE
WTF :  SyntaxError: Missing parentheses in call to 'print'

### ISSUE THREAD

**Issue by ZheFrenchKitchen** [Xinglab/rmats2sashimiplot#22]
`/home/bin/anaconda3/envs/python2/bin/rmats2sashimiplot --b1 bam_symlink_2017/T5rep1.bam,bam_symlink_2017/T5rep2.bam,bam_symlink_2017/T5rep3.bam --b2 bam_symlink_2017/unT5rep1.bam,bam_symlink_2017/unT5rep2.bam,bam_symlink_2017/unT5rep3.bam --l1 T5 --l2 UNT5 --exon_s 1 --intron_s 5 -o /data/data/sashimi -c chr16:-:24944500:24955500:GRCh38_PRIM_GENCODE_R25/gencode.v25.primary_assembly.annotation.gtf
`
>   File "/home/bin/anaconda3/envs/python2/lib/python2.7/site-packages/rmats2sashimiplot-2.0.2-py2.7.egg/MISO/misopy/index_gff.py", line 77
>     print "Making directory: %s" %(chrom_dir)
>                                ^
> SyntaxError: invalid syntax
>   File "/home/bin/anaconda3/envs/python2/lib/python2.7/site-packages/rmats2sashimiplot-2.0.2-py2.7.egg/MISO/misopy/sashimi_plot/sashimi_plot.py", line 46
>     print "WARNING: %s does not end in .miso_bf, are you sure it is the " \
>                                                                         ^
> SyntaxError: Missing parentheses in call to 'print'

**Comment by ShiehShieh** [comment]
This error could happen when you use python3. Could you please confirm which python version you're using?

**Comment by ZheFrenchKitchen** [comment]
Yeah my whole env is in python3 but i'm calling the script via python2 but it seems that it is calling  again python (and so python3 ) elsewhere in another dependencies ...so 2options :remove the harcoded call to python or source a python 2 virtual env before execution

**Comment by shannjiang** [comment]
Hi,

I encountered the same issue. Have you resolved it? How did you resolve it if it was resoved?

My whole env is also python3 but I am calling the script via python2.

thanks,

Shan

**Comment by LegebekeJ** [comment]
Anyone figured out what the issue is?

I got exactly the same error. Running the script via a conda environment using python 2.7.

**Comment by Rohit-Satyam** [comment]
Me too. Facing the same issue

**Comment by Nitin123-4** [comment]
Any solution for it???

**Comment by EricKutschera** [comment]
The changes in https://github.com/Xinglab/rmats2sashimiplot/pull/39 allow running with Python 2 even if the "python" found on the path is Python 3. Those changes also allow running with Python 3 after using 2to3.sh which was added to the repo.
