### ISSUE TITLE
P value instead of inclusion level in the plot

### ISSUE THREAD

**Issue by sridhar0605** [Xinglab/rmats2sashimiplot#23]
Hi @ShiehShieh and team

Thank you for developing this tool, 

please see below output of prpf8 gene from SE event, 

```
ID	GeneID	geneSymbol	chr	strand	exonStart_0base	exonEnd	upstreamES	upstreamEE	downstreamES	downstreamEE	ID	IJC_SAMPLE_1	SJC_SAMPLE_1	IJC_SAMPLE_2	SJC_SAMPLE_2	IncFormLen	SkipFormLen	PValue	FDR	IncLevel1	IncLevel2	IncLevelDifference
2538	"ENSG00000174231"	"PRPF8"	17	-	1564904	1565084	1564564	1564700	1565199	1565447	2538	205,264,466	0,15,0	289,623,384	1,2,1	200	100	0.00764948226388	0.133184362837	1.0,0.898,1.0	0.993,0.994,0.995	-0.028
2536	"ENSG00000174231"	"PRPF8"	17	-	1586826	1586995	1585422	1585587	1587765	1588101	2536	544,412,690	0,0,0	670,707,465	0,1,0	200	100	1	1.0	1.0,1.0,1.0	1.0,0.997,1.0	0.001
2537	"ENSG00000174231"	"PRPF8"	17	-	1581811	1581946	1580858	1580988	1582055	1582175	2537	210,167,355	0,1,0	279,596,370	0,0,0	200	100	1	1.0	1.0,0.988,1.0	1.0,1.0,1.0	-0.004
2539	"ENSG00000174231"	"PRPF8"	17	-	1577039	1577186	1576650	1576861	1577735	1577974	2539	264,245,457	2,0,1	384,551,421	0,0,0	200	100	1	1.0	0.985,1.0,0.996	1.0,1.0,1.0	-0.006
```

As you can see the inclusion levels above and below in the plot are different, looks like it uses p-value/fdr instead of inclusion level in the final plot (is there a way to avoid adding the inclusion value)

<img width="636" alt="screen shot 2017-12-07 at 10 36 51 am" src="https://user-images.githubusercontent.com/13422225/33726416-966f706c-db3a-11e7-9239-0ea1bf185bc6.png">

**Comment by ShiehShieh** [comment]
Hi @sridhar0605 ,

Looks like you're plotting SE event ID:2539. From rMATS's output, the inclusion level of this event are 0.985,1.0,0.996	1.0,1.0,1.0

The inclusion level shown on sashimiplot are rounded. Therefore, rmats2sashimiplot is plotting well, please review the plot and let me know if you have more question.

Thanks.

**Comment by sridhar0605** [comment]
@ShiehShieh  Thanks , should have guessed about rounded.
