### ISSUE TITLE
not recognizing bam files

### ISSUE THREAD

**Issue by seyfim** [Xinglab/rmats2sashimiplot#25]
Hello I am using the following command:
miso
 /cm/shared/apps/python/2.7.12/bin/rmats2sashimiplot  --b1 ./home/seyfim/isilon/NGS_Working/Marilyn_Seyfi/Stetson_STAR_replicate_bam/P14M3M4WtM1brainAligned.out.sorted.bam,./home/seyfim/isilon/NGS_Working/Marilyn_Seyfi/Stetson_STAR_replicate_bam/P14M3M4WtM3brainAligned.out.sorted.filtered.bam,./home/seyfim/isilon/NGS_Working/Marilyn_Seyfi/Stetson_STAR_replicate_bam/P14M3M4WtM3brainAligned.out.sorted.bam --b2 ./home/seyfim/isilon/NGS_Working/Marilyn_Seyfi/Stetson_STAR_replicate_bam/P14M3M4MutM2brainAligned.out.sorted.bam,./home/seyfim/isilon/NGS_Working/Marilyn_Seyfi/Stetson_STAR_replicate_bam/P14M3M4MutM2brain_accepted_hits.bam,./home/seyfim/isilon/NGS_Working/Marilyn_Seyfi/Stetson_STAR_replicate_bam/P14M3M4MutM3brainAligned.out.sorted.bam  -c chr12:-:4874271:4874336:./home/seyfim/lustre/rMATS/data/P14_candidategene.gff3 --l1 P14WT --l2 P14MUT -o ./home/seyfim/lustre/rMATS/data/sashimi_plots
 
 And I get the following error:
rmats2sashimiplot: error: Incorrect file type. Need to provide with the right bam files for --b1 and --b2
However, these are sorted and indexed bam files that I previously used when running rMATS v 3.2.5. Is there something that I am doing wrong? @ChengyangWang @ybucla @freedomyy @ShiehShieh

**Comment by noetrabanco** [comment]
Hello!
I am having the same error. I am runnig rmats2sashimiplot on Ubuntu (on a VirtualBox) where I shared the folder where I have my BAM files, that have been also used to run differential alternative splicing analyses with rMATS.
I'm using the folloeing command:
sudo rmats2sashimiplot --b1 ./media/windows/Drakkar21/AD5638.4363AA.markdup.sample.libs.bam,./media/windows/Drakkar21/AD5639.4364AA.markdup.sample.libs.bam,./media/windows/Drakkar21/AD5651.4373AA.markdup.sample.libs.bam --b2  ./media/windows/Drakkar28/AD5640.4365AA.markdup.sample.libs.bam,./media/windows/Drakkar28/AD5641.4366AA.markdup.sample.libs.bam,./media/windows/Drakkar28/AD5642.4367AA.markdup.sample.libs.bam -c  LK032270:-:58133:62437:./media/windows/JARILLOA.FA.v2.gff3 --l1 Drakkar21 --l2 Drakkar28 --exon_s 1 --intron_s 5 -o ./media/windows/sashimi_plots

**Comment by EricKutschera** [comment]
The error handling code was updated in https://github.com/Xinglab/rmats2sashimiplot/pull/38 to provide more details about why the --b1 or --b2 values were not able to be handled

Please open a new issue if needed after trying the latest source code
