### ISSUE TITLE
link to testData broken

### ISSUE THREAD

**Issue by leipzig** [Xinglab/rmats2sashimiplot#26]
http://www.mimg.ucla.edu/faculty/xing/rmats2sashimiplot/testData.tar needs updating

**Comment by EricKutschera** [comment]
The link to the test data was updated in https://github.com/Xinglab/rmats2sashimiplot/pull/41 to point to newly generated data. This is the new link: https://sourceforge.net/projects/rnaseq-mats/files/rmats2sashimiplot/rmats2sashimiplot_test_data.tar.gz/download
