### ISSUE TITLE
not generate event gff (related error: no entries found)

### ISSUE THREAD

**Issue by shihaoshen** [Xinglab/rmats2sashimiplot#27]
Program failed to generate gff in the Sashimi_index when all coordinates are right.

rmats2sashimiplot --b1 $bam/PC3E-1/PC3E-1Aligned.sort.bam,$bam/PC3E-2/PC3E-2Aligned.sort.bam,$bam/PC3E-3/PC3E-3Aligned.sort.bam --b2 $bam/GS689.LI-1/GS689.LI-1Aligned.sort.bam,$bam/GS689.LI-2/GS689.LI-2Aligned.sort.bam,$bam/GS689.LI-3/GS689.LI-3Aligned.sort.bam --l1 PC3E --l2 GS689 -c `sed -n ${SGE_TASK_ID}p $coord`:$gff --group-info $group -o $output`sed -n ${SGE_TASK_ID}p $gene`/ --min-counts 0 > ot.log
/mnt/isilon/xing_lab/shens/bin/anaconda2/envs/turbo/lib/python2.7/site-packages/matplotlib/cbook/deprecation.py:107: MatplotlibDeprecationWarning: The mpl_toolkits.axes_grid module was deprecated in version 2.1. Use mpl_toolkits.axes_grid1 and mpl_toolkits.axisartist provies the same functionality instead.
  warnings.warn(message, mplDeprecation, stacklevel=1)
Traceback (most recent call last):
  File "/mnt/isilon/xing_lab/shens/bin/anaconda2/envs/turbo/lib/python2.7/site-packages/rmats2sashimiplot-2.0.2-py2.7.egg/MISO/misopy/sashimi_plot/sashimi_plot.py", line 293, in <module>
    main()
  File "/mnt/isilon/xing_lab/shens/bin/anaconda2/envs/turbo/lib/python2.7/site-packages/rmats2sashimiplot-2.0.2-py2.7.egg/MISO/misopy/sashimi_plot/sashimi_plot.py", line 289, in main
    plot_label=plot_label)
  File "/mnt/isilon/xing_lab/shens/bin/anaconda2/envs/turbo/lib/python2.7/site-packages/rmats2sashimiplot-2.0.2-py2.7.egg/MISO/misopy/sashimi_plot/sashimi_plot.py", line 148, in plot_event
    %(event_name, pickle_dir)
Exception: Event chr14:74254063:74269974:+ not found in pickled directory /mnt/isilon/xing_lab/shens/ISO_ReRun/rMATS-iso-bak/Real_PC3E_Results/output_test/ASM5822_RP5-1021I20.1_ENSG00000259065/Sashimi_index. Are you sure this is the right directory for the event?
mv: cannot stat ‘/mnt/isilon/xing_lab/shens/ISO_ReRun/rMATS-iso-bak/Real_PC3E_Results/output_test/ASM5822_RP5-1021I20.1_ENSG00000259065/Sashimi_plot/chr14:74254063:74269974:+.pdf’: No such file or directory

<module 'misopy' from '/mnt/isilon/xing_lab/shens/bin/anaconda2/envs/turbo/lib/python2.7/site-packages/rmats2sashimiplot-2.0.2-py2.7.egg/MISO/misopy/__init__.pyc'>
Indexing GFF...
  - GFF: /mnt/isilon/xing_lab/shens/ISO_ReRun/rMATS-iso-bak/Real_PC3E_Results/output_test/ASM5822_RP5-1021I20.1_ENSG00000259065/Sashimi_index/tmp.gff3
  - Outputting to: /mnt/isilon/xing_lab/shens/ISO_ReRun/rMATS-iso-bak/Real_PC3E_Results/output_test/ASM5822_RP5-1021I20.1_ENSG00000259065/Sashimi_index
WARNING: No entries found for gene chr14:74254063:74269974:+ in GFF /mnt/isilon/xing_lab/shens/ISO_ReRun/rMATS-iso-bak/Real_PC3E_Results/output_test/ASM5822_RP5-1021I20.1_ENSG00000259065/Sashimi_index/tmp.gff3
Skipping gene chr14:74254063:74269974:+...
Loaded 0 genes
  - Loading of genes from GFF took 0.00 seconds
Outputting gene records in GFF format...
  - Output file: /mnt/isilon/xing_lab/shens/ISO_ReRun/rMATS-iso-bak/Real_PC3E_Results/output_test/ASM5822_RP5-1021I20.1_ENSG00000259065/Sashimi_index/genes.gff
  - Serialization of genes from GFF took 0.04 seconds
Indexing of GFF took 0.04 seconds.
[0;33;m
'/mnt/isilon/xing_lab/shens/ISO_ReRun/rMATS-iso-bak/PC3E_Bam//PC3E-1/PC3E-1Aligned.sort.bam' seems to be indexed already. Please Check out this index file '/mnt/isilon/xing_lab/shens/ISO_ReRun/rMATS-iso-bak/PC3E_Bam//PC3E-1/PC3E-1Aligned.sort.bam.bai'
'/mnt/isilon/xing_lab/shens/ISO_ReRun/rMATS-iso-bak/PC3E_Bam//PC3E-2/PC3E-2Aligned.sort.bam' seems to be indexed already. Please Check out this index file '/mnt/isilon/xing_lab/shens/ISO_ReRun/rMATS-iso-bak/PC3E_Bam//PC3E-2/PC3E-2Aligned.sort.bam.bai'
'/mnt/isilon/xing_lab/shens/ISO_ReRun/rMATS-iso-bak/PC3E_Bam//PC3E-3/PC3E-3Aligned.sort.bam' seems to be indexed already. Please Check out this index file '/mnt/isilon/xing_lab/shens/ISO_ReRun/rMATS-iso-bak/PC3E_Bam//PC3E-3/PC3E-3Aligned.sort.bam.bai'
'/mnt/isilon/xing_lab/shens/ISO_ReRun/rMATS-iso-bak/PC3E_Bam//GS689.LI-1/GS689.LI-1Aligned.sort.bam' seems to be indexed already. Please Check out this index file '/mnt/isilon/xing_lab/shens/ISO_ReRun/rMATS-iso-bak/PC3E_Bam//GS689.LI-1/GS689.LI-1Aligned.sort.bam.bai'
'/mnt/isilon/xing_lab/shens/ISO_ReRun/rMATS-iso-bak/PC3E_Bam//GS689.LI-2/GS689.LI-2Aligned.sort.bam' seems to be indexed already. Please Check out this index file '/mnt/isilon/xing_lab/shens/ISO_ReRun/rMATS-iso-bak/PC3E_Bam//GS689.LI-2/GS689.LI-2Aligned.sort.bam.bai'
'/mnt/isilon/xing_lab/shens/ISO_ReRun/rMATS-iso-bak/PC3E_Bam//GS689.LI-3/GS689.LI-3Aligned.sort.bam' seems to be indexed already. Please Check out this index file '/mnt/isilon/xing_lab/shens/ISO_ReRun/rMATS-iso-bak/PC3E_Bam//GS689.LI-3/GS689.LI-3Aligned.sort.bam.bai'
[0m

**Comment by JamalELH** [comment]
Dear all,

I'm also having exactly the same error when using rmats2sashimiplot with hg38 GTF3 annotation file from gencode v27.
The -c coordinates:annotationfile.gff3" option in the description says that .gff3 should provide annotation of genes and transcripts in gff3 so my file should be fine. 

Could you please help us with this issue?
Thank you in advance,
Best regards,
Jamal.

**Comment by LegebekeJ** [comment]
Did anyone figure out this issue? I get the same error. 

I'm using hg38 gff3 file, using the right coordinates etc. The gene is listed in the genes.gff file and the tmp.gff3 file contains the exons of that gene. However, somehow apparently it's not finding the gene in the tmp.gff3 file...

**Comment by EricKutschera** [comment]
"WARNING: No entries found for gene ..." may be due to the annotation file using "transcript" rather than "mRNA". The changes in https://github.com/Xinglab/rmats2sashimiplot/pull/37 allow the annotation file to use either "transcript" or "mRNA".

Please open a new issue if needed after trying the latest source code
