### ISSUE TITLE
pysam import issue, no pdf output

### ISSUE THREAD

**Issue by AmrR101** [Xinglab/rmats2sashimiplot#30]
Hello - I tried installing rmats2sashimiplot via bioconda and just by pip install as well. For some reason pysam import seems to fail (I think). I am pasting the output example below.

`"<module 'misopy' from '/opt/miniconda2/lib/python2.7/site-packages/rmats2sashimiplot-2.0.2-py2.7.egg/MISO/misopy/__init__.pyc'>
Indexing GFF...
/Users/a/Documents/3620sashimi/se60x_sashimiplot_SE/Sashimi_index_ZNF664_1/tmp.gff3 appears to already be indexed. Aborting.
python /opt/miniconda2/lib/python2.7/site-packages/rmats2sashimiplot-2.0.2-py2.7.egg/MISO/misopy/sashimi_plot/sashimi_plot.py --plot-event "chr12:123988046:123988138:+@chr12:123989309:123989442:+@chr12:124011381:124011441:+" /Users/a/Documents/3620sashimi/se60x_sashimiplot_SE/Sashimi_index_ZNF664_1 /Users/a/Documents/3620sashimi/se60x_sashimiplot_SE/Sashimi_index_ZNF664_1/sashimi_plot_settings.txt --output-dir /Users/a/Documents/3620sashimi/se60x_sashimiplot_SE/Sashimi_plot
Traceback (most recent call last):
  File "/opt/miniconda2/lib/python2.7/site-packages/rmats2sashimiplot-2.0.2-py2.7.egg/MISO/misopy/sashimi_plot/sashimi_plot.py", line 23, in <module>
    import pysam
  File "/opt/miniconda2/lib/python2.7/site-packages/pysam/__init__.py", line 4, in <module>
    from pysam.libchtslib import *
ImportError: dlopen(/opt/miniconda2/lib/python2.7/site-packages/pysam/libchtslib.so, 2): Library not loaded: @rpath/libcrypto.1.0.0.dylib
  Referenced from: /opt/miniconda2/lib/python2.7/site-packages/pysam/libchtslib.so
  Reason: image not found
mv: rename /Users/a/Documents/3620sashimi/se60x_sashimiplot_SE/Sashimi_plot/chr12:123988046:123988138:+@chr12:123989309:123989442:+@chr12:124011381:124011441:+.pdf to /Users/a/Documents/3620sashimi/se60x_sashimiplot_SE/Sashimi_plot/1_ZNF664_chr12_123988046_123988138_+@chr12_123989309_123989442_+@chr12_124011381_124011441_+.pdf: No such file or directory"`

**Comment by EricKutschera** [comment]
It seems like it may be an issue with the pysam install rather than rmats2sashimiplot. If you start a python interpreter can you run `import pysam`?

Maybe you could try creating a new conda environment and installing the rmats2sashimiplot dependencies

`conda create --prefix ./new_conda_env`
`conda activate ./new_conda_env/`
`conda install -c conda-forge -c bioconda python=2 numpy scipy matplotlib pysam samtools bedtools`

Then you can run rmats2sashimiplot directly from the latest source code: `python ./src/rmats2sashimiplot/rmats2sashimiplot.py`

**Comment by naqvia** [comment]
I have tried the above (also tried with the example input files) and I am still getting an import issue: 

```
Traceback (most recent call last):
  File "/Users/aan/Desktop/rmats2sashimiplot/src/MISO/misopy/sashimi_plot/sashimi_plot.py", line 23, in <module>
    import pysam
  File "/Users/aan/Desktop/yes/envs/rmats2sushami/lib/python2.7/site-packages/pysam/__init__.py", line 4, in <module>
    from pysam.libchtslib import *
ImportError: dlopen(/Users/aan/Desktop/yes/envs/rmats2sushami/lib/python2.7/site-packages/pysam/libchtslib.so, 2): Library not loaded: @rpath/libcrypto.1.0.0.dylib
  Referenced from: /Users/aan/Desktop/yes/envs/rmats2sushami/lib/python2.7/site-packages/pysam/libchtslib.so
  Reason: image not found
mv: rename /Users/aan/Desktop/test_coordinate_output/Sashimi_plot/chr1:9000:25001:+.pdf to /Users/aan/Desktop/test_coordinate_output/Sashimi_plot/chr1_9000_25001_+.pdf: No such file or directory
```

Do you know what's going on?

**Comment by naqvia** [comment]
Ok, I got it to work, by running from the src as opposed to installing rMATs. I have another issue though. I keep on getting: `Exception: Event chr6:33572412:33580297:- not found in pickled directory /Users/naqvia/Desktop/test_coordinate_output_v2/Sashimi_index. Are you sure this is the right directory for the event?`

Please advise.

**Comment by EricKutschera** [comment]
The error `not found in pickled directory` could be from running with the same output directory command line argument as a previous run that had an error. You could try running again, but using a new output directory path or removing your old output directory

**Comment by AmrR101** [comment]
I got it working by avoiding the conda environment all together. Using correct versions of dependencies, the issue was resolved.
