### ISSUE TITLE
Error: Must provide a coverage value for each sample or leave coverages unset.

### ISSUE THREAD

**Issue by archana433** [Xinglab/rmats2sashimiplot#32]
ran  python sashimi_plot.py --plot-event  and got this error

**Comment by EricKutschera** [comment]
rmats2sashimiplot calls ./src/MISO/misopy/sashimi_plot/sashimi_plot.py to generate the plot(s) after appropriately processing the inputs. Errors from calling sashimi_plot.py directly are outside of the scope of rmats2sashimiplot
