### ISSUE TITLE
RPKM values are in double digits or less. What am I doing wrong?

### ISSUE THREAD

**Issue by mranjan1** [Xinglab/rmats2sashimiplot#40]
Hi all, I hope this is not a repost. I have this issue where my plot is showing extremely low RPKM values on the axis and the Inclevel values on the plot are missing too whereas I can see the IncLevel values in the rMATS file and have verified RPKM values to be in few thousands.

About the data: 

150bp PE human data aligned using STAR

Genome: GRCh38.p13.genome.fa 
GTF: gencode.v34.annotation.gtf
GFF: gencode.v34.annotation.gff3 (wasn't working untill I came across Eric's workaround of using:  sed 's/\([^\t]*\t[^\t]*\t\)transcript\t/\1mRNA\t/' /path/file.gff3 > /path/file_mrna.gff3)

STAR parameters:
--alignEndsType EndToEnd  
--outSAMmapqUnique 60 
--outSAMtype BAM Unsorted  

BAM files were sorted and indexed using Samtools

rMATS command:

`python rmats.py --b1 ./bam_col/b1.txt --b2 ./bam_col/b2.txt --gtf ./genome/gencode.v34.annotation.gtf  --od ./diff_col/ -t paired --nthread 20  --readLength 150 --cstat 0.0001 `

The SE.MATS.JC.txt file created, includes over 62k lines so I decided to filter it by FDR<=0.1 which gave me around 700 candidates.  

rmats2sashimiplot command:

`rmats2sashimiplot --b1 ./P1_D0.Aligned.sorted.bam,./P2_D0.Aligned.sorted.bam,./P3_D0.Aligned.sorted.bam,./P4_D0.Aligned.sorted.bam,./P5_D0.Aligned.sorted.bam,./P6_D0.Aligned.sorted.bam --b2 ./P1_D100.Aligned.sorted.bam,./P2_D100.Aligned.sorted.bam,./P3_D100.Aligned.sorted.bam,./P4_D100.Aligned.sorted.bam,./P5_D100.Aligned.sorted.bam,./P6_D100.Aligned.sorted.bam -t SE -e ./SE.MATS.JC_filtered.txt --l1 VitD_0nM --l2 VitD_100nM --exon_s 1 --intron_s 5 -o ./sashimi/SE_filtered --group-info ./grouping.gf`

grouping.gf content:

VitD_0nM: 1-6
VitD_100nM: 7-12

Additionally: I get his error when running the rmats2sashimiplot command: 

Saving plot to:./bam_sort/col_sort_bam/sashimi/SE_filtered/Sashimi_plot/chrX:73944584:73944662:+@chrX:73946999:73947096:+@chrX:73984444:73984541:+.pdf
Warning: The inclusion levels of Event 'chrX:73944327:73944662:+@chrX:73946999:73947374:+@chrX:73984444:73984541:+' contains 'NA' value, which could lead to unexpected output.
<module 'misopy' from '/usr/local/lib/python2.7/dist-packages/rmats2sashimiplot-2.0.2-py2.7.egg/MISO/misopy/__init__.pyc'>
Indexing GFF...
  - GFF:./bam_sort/col_sort_bam/sashimi/SE_filtered/Sashimi_index_JPX_57/tmp.gff3
  - Outputting to:./bam_sort/col_sort_bam/sashimi/SE_filtered/Sashimi_index_JPX_57
Through 0 genes...
Loaded 1 genes
  - Loading of genes from GFF took 0.00 seconds
Making directory:./bam_sort/col_sort_bam/sashimi/SE_filtered/Sashimi_index_JPX_57/chrX
  - Chromosome serialization took 0.00 seconds
Outputting gene records in GFF format...
  - Output file:./bam_sort/col_sort_bam/sashimi/SE_filtered/Sashimi_index_JPX_57/genes.gff
  - Serialization of genes from GFF took 0.02 seconds
Indexing of GFF took 0.02 seconds.
python /usr/local/lib/python2.7/dist-packages/rmats2sashimiplot-2.0.2-py2.7.egg/MISO/misopy/sashimi_plot/sashimi_plot.py --plot-event "chrX:73944327:73944662:+@chrX:73946999:73947374:+@chrX:73984444:73984541:+"./bam_sort/col_sort_bam/sashimi/SE_filtered/Sashimi_index_JPX_57./bam_sort/col_sort_bam/sashimi/SE_filtered/Sashimi_index_JPX_57/sashimi_plot_settings.txt --output-dir./bam_sort/col_sort_bam/sashimi/SE_filtered/Sashimi_plot
/home/nb/.local/lib/python2.7/site-packages/matplotlib/cbook/deprecation.py:107: MatplotlibDeprecationWarning: The mpl_toolkits.axes_grid module was deprecated in version 2.1. Use mpl_toolkits.axes_grid1 and mpl_toolkits.axisartist provies the same functionality instead.
  warnings.warn(message, mplDeprecation, stacklevel=1)
Reading settings from:./bam_sort/col_sort_bam/sashimi/SE_filtered/Sashimi_index_JPX_57/sashimi_plot_settings.txt

I don't see any NA values in my SE.MATS.JC.txt file. What is triggering this warning? Is this the reason every single one of my plot is missing the IncLevel value?

Thanks!

[274_MLH3_chr14_75038340_75038412_-@chr14_75033419_75033490_-@chr14_75032068_75032179_-.pdf](https://github.com/Xinglab/rmats2sashimiplot/files/4885799/274_MLH3_chr14_75038340_75038412_-%40chr14_75033419_75033490_-%40chr14_75032068_75032179_-.pdf)

**Comment by EricKutschera** [comment]
The warning about NA values is from here: https://github.com/Xinglab/rmats2sashimiplot/blob/master/src/rmats2sashimiplot/rmats2sashimiplot.py#L213

If you don't see NA in SE.MATS.JC_filtered.txt then another possible cause is having too few values in the IncLevel columns of that file. Could you post that SE.MATS file (or just the header and a few rows)?

The RPKM values are calculated here https://github.com/Xinglab/rmats2sashimiplot/blob/master/src/MISO/misopy/sashimi_plot/plot_utils/plot_gene.py#L88

I'm not sure what is causing the low RPKM values. Maybe you could try adding some print statements to debug?

**Comment by mranjan1** [comment]
Hi Eric,

thank you so much. I've attached both, the complete rMATS output file and the filtered file (FDR≤ 0.1). I did a simple text search and couldn't find any 'na' values.

I won't be able to debug this on my own right away due to my superficial knowledge of Python but I'll try to find a tutorial.

Please let me know if I can provide any additional details.

[SE.MATS.JC_filtered.txt](https://github.com/Xinglab/rmats2sashimiplot/files/4896745/SE.MATS.JC_filtered.txt)

[SE.MATS.JC.txt](https://github.com/Xinglab/rmats2sashimiplot/files/4896715/SE.MATS.JC.txt)

**Comment by EricKutschera** [comment]
SE.MATS.JC_filtered.txt changed the values. Here's an example row

SE.MATS.JC_filtered.txt:
`217	ENSG00000178623.12	GPR35	chr2	+	240606386	240606612	240605429	240605570	240616387	240616511	217	"582,742,573,245,475,000"	"1,5,2,1,6,5"	"723,357,445,269,460,000"	"11,9,8,5,9,19"	298	149	3.33E-08	0.000116173	"0.997,0.987,0.993,0.992,0.975,0.982"	"0.97,0.952,0.965,0.964,0.962,0.922"	0.032`

SE.MATS.JC.txt
`217	"ENSG00000178623.12"	"GPR35"	chr2	+	240606386	240606612	240605429	240605570	240616387	240616511	217	582,742,573,245,475,551	1,5,2,1,6,5	723,357,445,269,460,449	11,9,8,5,9,19	298	149	3.32708335327e-08	0.000116172508798	0.997,0.987,0.993,0.992,0.975,0.982	0.97,0.952,0.965,0.964,0.962,0.922	0.032`

Some columns have the quotes removed, some have quotes added, and some are rounded.

I've attached a python script (renamed to .txt to allow attachment) that does the filtering without changing the values and also the filtered file after running the script. That should fix the nan inc levels, but the RPKM values may be a different issue.
[SE.MATS.JC_filtered_2.txt](https://github.com/Xinglab/rmats2sashimiplot/files/4897196/SE.MATS.JC_filtered_2.txt)
[filter_py.txt](https://github.com/Xinglab/rmats2sashimiplot/files/4897198/filter_py.txt)

**Comment by mranjan1** [comment]
Hi Eric,

thank you so much for the conversion script. It worked like a charm. The plots are now showing IncLevel values. 

The low RPKM values remain a problem. It may take me some time but I'll try to run completely different data set to see if the problem persists.

I really appreciate your help.
