### ISSUE TITLE
not working at all

### ISSUE THREAD

**Issue by feedmewifi** [Xinglab/rmats2sashimiplot#45]
I run the following command:

`/path/rmats2sashimiplot/src/rmats2sashimiplot/rmats2sashimiplot.py --b1 bam,bam,bam --b2 bam,bam,bam -t SE -e /path/rMATS_output/SE.MATS.JCEC.txt --l1 WT --l2 480/480 -o /path/significant_SE_wtvs480480_grouped_sashimi_plots --group-info /path/wt_vs_480480_groups.gf --color #808080,#000000 --no-text-background`

I get this result:
```
import: unable to open X server `' @ error/import.c/ImportImageCommand/369.
import: unable to open X server `' @ error/import.c/ImportImageCommand/369.
import: unable to open X server `' @ error/import.c/ImportImageCommand/369.
import: unable to open X server `' @ error/import.c/ImportImageCommand/369.
/path/rmats2sashimiplot/src/rmats2sashimiplot/rmats2sashimiplot.py: line 9: syntax error near unexpected token `('
/path/rmats2sashimiplot/src/rmats2sashimiplot/rmats2sashimiplot.py: line 9: `def convert_sam2bam(options):'
```

This happens whether or not I've run 2to3.sh

**Comment by EricKutschera** [comment]
rmats2sashimiplot.py isn't meant to be used as the first part of a command line. It looks like your error might be because that python file is being interpreted as a shell script. Try adding python to the beginning of the command: `python /path/rmats2sashimiplot/src/rmats2sashimiplot/rmats2sashimiplot.py ...`

**Comment by feedmewifi** [comment]
> rmats2sashimiplot.py isn't meant to be used as the first part of a command line. It looks like your error might be because that python file is being interpreted as a shell script. Try adding python to the beginning of the command: `python /path/rmats2sashimiplot/src/rmats2sashimiplot/rmats2sashimiplot.py ...`

this worked!
