### ISSUE TITLE
Warning: The inclusion levels of Event contains 'NA' value, which could lead to unexpected output.

### ISSUE THREAD

**Issue by feedmewifi** [Xinglab/rmats2sashimiplot#46]
I run the following command:

`/path/rmats2sashimiplot/src/rmats2sashimiplot/rmats2sashimiplot.py --b1 bam,bam,bam --b2 bam,bam,bam -t SE -e /path/rMATS_output/SE.MATS.JCEC.txt --l1 WT --l2 480/480 -o /path/significant_SE_wtvs480480_grouped_sashimi_plots --group-info /path/wt_vs_480480_groups.gf --color #808080,#000000 --no-text-background`

For every single gene, I get this warning:
```
Warning: The inclusion levels of Event '7:138845957:138846273:-@7:138840577:138840934:-@7:138835823:138837030:-' contains 'NA' value, which could lead to unexpected output.

```

This is reflected in the plots, which say for example "Sorbs1 WT IncLevel: nan"
I know my rMATS file has no NA values in it.

**Comment by EricKutschera** [comment]
Here's the source code that produces that warning: https://github.com/Xinglab/rmats2sashimiplot/blob/master/src/rmats2sashimiplot/rmats2sashimiplot.py#L213

If it has any exception while trying to parse the IncLevel values from the rmats file then it will just use NA. It could be that the number of values in the rmats file doesn't match with the number of b1 and b2 inputs. Or it could be some other issue with the file. You could try adding some print statements around that line to figure out what's happening
