### ISSUE TITLE
query length in RPKM

### ISSUE THREAD

**Issue by wangjiawen2013** [Xinglab/rmats2sashimiplot#49]
Dear,
In plots generated by rmats2sashimiplot, The y-axis represents a modified RPKM value:
![image](https://user-images.githubusercontent.com/29703450/101152563-3b9e7c00-365e-11eb-9518-313206da872d.png)

But what does query length mean ? RPKM is usually used to measure gene expression abundance, and each gene only has one RPKM. while In sashimiplot, it seems that each nucleotide site has a RPKM value (or read density), so what does it mean ? what's the difference between RPKM and coverage (as shown in Integrative Genomics Viewer (IGV) ) ?

**Comment by EricKutschera** [comment]
Query length is the length of the read sequence. Each read distributes its read count evenly over the nucleotide sites it was mapped to. If the read is length 50 then each individual nucleotide site gets 1/50 added to its value. The value at each site is aggregated across all reads. Then the value is normalized by the total number of reads and the two constants (1,000 and 1,000,000). The formula could be written as:

```
1e9 * sum_over_reads(1/length_of_this_read)
/
total_number_of_reads
```

Here's the code for that calculation: https://github.com/Xinglab/rmats2sashimiplot/blob/master/src/MISO/misopy/sashimi_plot/plot_utils/plot_gene.py#L88

From the IGV documentation of "Coverage Track": https://software.broadinstitute.org/software/igv/AlignmentData
It seems like it is just the raw number of reads mapped to each nucleotide site (along with the counts of each individiual ACGT). So putting it in the same format as the above formula it's essentially just:
`sum_over_reads(1)`
