### ISSUE TITLE
problem in rmats2sashimiplot install

### ISSUE THREAD

**Issue by noahpieta** [Xinglab/rmats2sashimiplot#5]
hello! i'm try to use rmats2sashimiplot but come across a problem.
when i run rmats2sashimiplot, it reports:
![rmats2](https://cloud.githubusercontent.com/assets/9362155/17130709/82dc0c26-534c-11e6-95cc-af9f8b0873be.JPG)
would you help me to solve it? Thank you very much!!!!!

**Comment by BioNinja** [comment]
@ShiehShieh , why not submit this package to pypi or bioconda? rmats2sashimiplot will be easier to install like this:

    pip install rmats2sashimiplot
    # or bioconda
    conda install -c bioconda rmats2sashimiplot

**Comment by bahramis** [comment]
@noahpieta Please check if you downloaded the final version. You error seems to me you've had an installation issue, please uninstall and install the package again. Also, read the instruction carefully to make sure you have the correct python version installed on your system.

**Comment by bahramis** [comment]
@BioNinja Thanks for the suggestion. While it is fairly easy to install the package right now (just by running "python setup.py install"), we will ultimately submit the package to pypi.
