### ISSUE TITLE
invalid syntax

### ISSUE THREAD

**Issue by llywelyng** [Xinglab/rmats2sashimiplot#51]
Hi, I'm trying to run the pipeline on the test data, but I get the following error message:

...

File "src/rmats2sashimiplot/rmats2sashimiplot.py", line 186
    " which could lead to unexpected output.".format(id_str), file=sys.stderr)
                                                                  ^
SyntaxError: invalid syntax

...

My input code is: 

...
python src/rmats2sashimiplot/rmats2sashimiplot.py --b1 rmats2sashimiplot_test_data/sample_1_replicate_1.bam,rmats2sashimiplot_test_data/sample_1_replicate_2.bam,rmats2sashimiplot_test_data/sample_1_replicate_3.bam \
--b2 rmats2sashimiplot_test_data/sample_2_replicate_1.bam,rmats2sashimiplot_test_data/sample_2_replicate_2.bam,rmats2sashimiplot_test_data/sample_2_replicate_3.bam \
-c chr16:+:9000:25000:rmats2sashimiplot_test_data/annotation.gff3 \
--l1 samp2 \
--l2 samp1 \
--exon_s 1 \
--intron_s 5 \
-o sashi_test
...

I then tried to install it using 'python ./setup.py install', and half way down the output I get a similar error:

....

byte-compiling build/bdist.linux-x86_64/egg/MISO/misopy/pe_utils.py to pe_utils.pyc
byte-compiling build/bdist.linux-x86_64/egg/MISO/misopy/json_utils.py to json_utils.pyc
byte-compiling build/bdist.linux-x86_64/egg/MISO/misopy/cluster_utils.py to cluster_utils.pyc
byte-compiling build/bdist.linux-x86_64/egg/MISO/misopy/miso.py to miso.pyc
byte-compiling build/bdist.linux-x86_64/egg/MISO/misopy/gff_utils.py to gff_utils.pyc
  File "build/bdist.linux-x86_64/egg/MISO/misopy/gff_utils.py", line 304
    print("Outputting sliced GFF records to: %s" %(filename), file=sys.stderr)
                                                                  ^
SyntaxError: invalid syntax

...

Any help would be much appreciated!

**Comment by EricKutschera** [comment]
It looks like you are not using the latest code. It also looks like you ran [2to3.sh](https://github.com/Xinglab/rmats2sashimiplot/blob/f00b88f1c0db462f469e8d3d1c9efbdef6da1928/2to3.sh) but are using python 2. I think you could get things working by using the latest commit without running 2to3.sh

I could reproduce the error message you posted by using this commit (which is the most recent tagged release v2.0.3, but actually there are some improvements in the latest master branch commit): https://github.com/Xinglab/rmats2sashimiplot/commit/2b8cd4e1db8fa618624f71099854e7aba0e74bc1

* `git clone https://github.com/Xinglab/rmats2sashimiplot.git`
* `cd rmats2sashimiplot`
* `git checkout 2b8cd4e1db8fa618624f71099854e7aba0e74bc1`
* `curl -L -o rmats2sashimiplot_test_data.tar.gz https://sourceforge.net/projects/rnaseq-mats/files/rmats2sashimiplot/rmats2sashimiplot_test_data.tar.gz/download`
* `tar -xvf ./rmats2sashimiplot_test_data.tar.gz`
* `2to3 -w -n src`
* `python src/rmats2sashimiplot/rmats2sashimiplot.py --b1 ./rmats2sashimiplot_test_data/sample_1_replicate_1.bam,./rmats2sashimiplot_test_data/sample_1_replicate_2.bam,./rmats2sashimiplot_test_data/sample_1_replicate_3.bam --b2 ./rmats2sashimiplot_test_data/sample_2_replicate_1.bam,./rmats2sashimiplot_test_data/sample_2_replicate_2.bam,./rmats2sashimiplot_test_data/sample_2_replicate_3.bam -c chr16:+:9000:25000:rmats2sashimiplot_test_data/annotation.gff3 --l1 samp2 --l2 samp1 --exon_s 1 --intron_s 5 -o sashi_test`

You could run with the latest code with:

* `git clone https://github.com/Xinglab/rmats2sashimiplot.git`
* `cd rmats2sashimiplot`
* `curl -L -o rmats2sashimiplot_test_data.tar.gz https://sourceforge.net/projects/rnaseq-mats/files/rmats2sashimiplot/rmats2sashimiplot_test_data.tar.gz/download`
* `tar -xvf ./rmats2sashimiplot_test_data.tar.gz`
* `python src/rmats2sashimiplot/rmats2sashimiplot.py --b1 ./rmats2sashimiplot_test_data/sample_1_replicate_1.bam,./rmats2sashimiplot_test_data/sample_1_replicate_2.bam,./rmats2sashimiplot_test_data/sample_1_replicate_3.bam --b2 ./rmats2sashimiplot_test_data/sample_2_replicate_1.bam,./rmats2sashimiplot_test_data/sample_2_replicate_2.bam,./rmats2sashimiplot_test_data/sample_2_replicate_3.bam -c chr16:+:9000:25000:rmats2sashimiplot_test_data/annotation.gff3 --l1 samp2 --l2 samp1 --exon_s 1 --intron_s 5 -o sashi_test`

**Comment by llywelyng** [comment]
Yay that worked! Thanks a lot for your help!
