### ISSUE TITLE
color feature

### ISSUE THREAD

**Issue by EEnakagak** [Xinglab/rmats2sashimiplot#52]
Hi,
I am new to command lines and I am sorry if this is a silly mistake. Somehow I am not able to use the color argument not even with the test files. I tried the following simplified test line:

rmats2sashimiplot --b1 ./rmats2sashimiplot_test_data/sample_1_replicate_1.bam --b2 ./rmats2sashimiplot_test_data/sample_2_replicate_1.bam -c chr16:+:9000:25000:./rmats2sashimiplot_test_data/annotation.gff3 --l1 SampleOne --l2 SampleTwo --exon_s 1 --intron_s 5 --color [#808080,#000000] -o test_coordinate_output

I get the following error when I try to change colors:

ValueError: Invalid RGBA argument: '['

If I try the argument color without [, it returns: expected one argument.

I have attached the full screen in here.

Thanks,
Erick
[colour_error.docx](https://github.com/Xinglab/rmats2sashimiplot/files/6052763/colour_error.docx)

**Comment by EricKutschera** [comment]
The color argument can be given with single quotes (`'`) like: `--color '#808080,#000000'`

The single quotes means that the program will see exactly what's in the quotes. Without the quotes the `#` could be interpreted as starting a comment which would cause the "expected one argument" error you saw
