### ISSUE TITLE
missing junction on a plot

### ISSUE THREAD

**Issue by Vita-github** [Xinglab/rmats2sashimiplot#57]
Hi!
Thank you for your wonderful tool to visualize RNAseq data. I have a question regarding filtering of junction reads - I am unable to plot junction reads, that I clearly see on a bam file (I am not using the min-junction parameter). The junctions are present in a patient sample as a consequence of a splicing variant, but not in a control sample. Could you help me visualize the junction?

![missing-junction](https://user-images.githubusercontent.com/61147571/113732227-b3a6ac80-96f9-11eb-8f2d-d34fd1615496.jpg)

Thank you for your help! 

Vita

**Comment by EricKutschera** [comment]
rmats2sashimiplot will only plot the line showing the junction count if it knows about the junction from the event file or annotation file. It looks like you are using rmats2sashimiplot with `-c coordinates:/path/to/gff3` so the gff3 file would need to have that junction in one of the transcripts. You could try adding a transcript with that junction to the gff3 file and then rerunning rmats2sashimiplot

If the junction is already in the annotation file then it may be that rmats2sashimiplot is filtering out all of the alignments that include that junction. The only reason that alignments are filtered is if they include an insertion or deletion in the cigar

**Comment by Vita-github** [comment]
That worked!! Thank you :)
