### ISSUE TITLE
Bam file indexing error

### ISSUE THREAD

**Issue by akshaya-v** [Xinglab/rmats2sashimiplot#58]
Hello rMATS team!

I am trying to use bam files as input to rmats2sashimiplot. However, since the genome size of the species I am working on is large with many chromosomes larger than 512 Mb in size, I can only generate the csi index for the bam files. I do have the csi index in the same location as the bam files. However, I receive the following error:
 
> [E::hts_idx_check_range] Region 536937569..536937720 cannot be stored in a bai index. Try using a csi index
> [E::sam_index] Read 'A00977:192:HLMW2DSXY:3:2523:21287:23109' with ref_name='1A', ref_length=594102056, flags=163, pos=536937570 cannot be indexed

Could you please advise if csi indices are compatible with rmats2sashimiplot or is there any workaround to fix this issue.

Thanks.

**Comment by EricKutschera** [comment]
I think this change (https://github.com/Xinglab/rmats2sashimiplot/pull/59) should allow you to run rmats2sashimiplot if you have already created the csi index files. Can you try running with the source code from that commit?

**Comment by akshaya-v** [comment]
Hello Eric,
Thank you very much for the response. I ran with the source code from the commit and it works fine now.
