### ISSUE TITLE
rmats2sashimiplot: error: argument --exon_s: invalid int value: './SE.MATS.JC.txt'

### ISSUE THREAD

**Issue by sr8510** [Xinglab/rmats2sashimiplot#62]
Hello,

I succeeded into getting rMATs output, which was great actually. Now I am trying to use rmats2sashimiplot to plot the genes in my rMATs output. As Miso had issues running on python 3.8 which caused rmats2sashimiplot to fail when I used it from the command line, I created a conda env with python 2.7 to include Miso and rmats2sashimiplot. I used the same script provided in the manual:
rmats2sashimiplot --b1  {group1 bam files} --b2 {group 2 bam files} --t SE --e ./SE.MATS.JCEC.txt --l1 grp1 --l2 grp2 --exon_s 1 --intron_s 5 --o SE_grouped_output --group-info SE.gf
But I got this error: rmats2sashimiplot: error: argument --exon_s: invalid int value: './SE.MATS.JC.txt' 
I am not sure what's the issue here

Thanks

**Comment by EricKutschera** [comment]
I think the issue is that you are using two dashes `--` instead of one for `-e ./SE.MATS.JC.txt` (also `--o` instead of `-o` and `--t` instead of `-t`). rmats2sashimiplot has two arguments that start with `e`: `-e EVENTS_FILE` and `--exon_s EXON_S`. rmats2sashimiplot is using argparse which allows shortened argument names, so it thinks that `--e` is short for `--exon_s`: https://docs.python.org/3/library/argparse.html#allow-abbrev

**Comment by sr8510** [comment]
Thanks a lot. I made a mistake when typing the code. However, after running it, I ran into another issue, which am not sure if it is related to Miso or to rmats2sashimiplot. 
I used the same code as above (with SE and with A3SS event files) and I got this error:

Traceback (most recent call last):
  File "/home/user/anaconda3/envs/miso/lib/python2.7/site-packages/MISO/misopy/index_gff.py", line 204, in <module>
    main()
  File "/home/user/anaconda3/envs/miso/lib/python2.7/site-packages/MISO/misopy/index_gff.py", line 196, in main
    compress_id=options.compress_id)
  File "/home/user/anaconda3/envs/miso/lib/python2.7/site-packages/MISO/misopy/index_gff.py", line 167, in index_gff
    compress_id=compress_id)
  File "/home/user/anaconda3/envs/miso/lib/python2.7/site-packages/MISO/misopy/index_gff.py", line 100, in serialize_genes
    gene_filename)
  File "/home/user/anaconda3/envs/miso/lib/python2.7/site-packages/MISO/misopy/pickle_utils.py", line 17, in write_pickled_file
    pickled_file = open(pickled_filename, 'wb')
IOError: [Errno 71] Protocol error: '/media/sf_H_DRIVE/rMats/Sashimi/SE_grouped_output/Sashimi_index_STAB1_329/chr3/chr3:52518723:52518869:+@chr3:52519185:52519404:+@chr3:52519245:52519404:+.pickle'
/home/user/anaconda3/envs/miso/bin/python /home/sherif/anaconda3/envs/miso/lib/python2.7/site-packages/MISO/misopy/sashimi_plot/sashimi_plot.py --plot-event "chr3:52518723:52518869:+@chr3:52519185:52519404:+@chr3:52519245:52519404:+" /media/sf_H_DRIVE/rMats/Sashimi/SE_grouped_output/Sashimi_index_STAB1_329 /media/sf_H_DRIVE/rMats/Sashimi/SE_grouped_output/Sashimi_index_STAB1_329/sashimi_plot_settings.txt --output-dir /media/sf_H_DRIVE/rMats/Sashimi/SE_grouped_output/Sashimi_plot
/home/user/anaconda3/envs/miso/lib/python2.7/site-packages/matplotlib/cbook/deprecation.py:107: MatplotlibDeprecationWarning: The mpl_toolkits.axes_grid module was deprecated in version 2.1. Use mpl_toolkits.axes_grid1 and mpl_toolkits.axisartist provies the same functionality instead.
  warnings.warn(message, mplDeprecation, stacklevel=1)
Traceback (most recent call last):
  File "/home/user/anaconda3/envs/miso/lib/python2.7/site-packages/MISO/misopy/sashimi_plot/sashimi_plot.py", line 293, in <module>
    main()
  File "/home/user/anaconda3/envs/miso/lib/python2.7/site-packages/MISO/misopy/sashimi_plot/sashimi_plot.py", line 289, in main
    plot_label=plot_label)
  File "/home/user/anaconda3/envs/miso/lib/python2.7/site-packages/MISO/misopy/sashimi_plot/sashimi_plot.py", line 142, in plot_event
    %(genes_filename)
Exception: Cannot find file /media/sf_H_DRIVE/rMats/Sashimi/SE_grouped_output/Sashimi_index_STAB1_329/genes_to_filenames.shelve. Are you sure the events were indexed with the latest version of index_gff.py?
mv: cannot stat '/media/sf_H_DRIVE/rMats/Sashimi/SE_grouped_output/Sashimi_plot/chr3:52518723:52518869:+@chr3:52519185:52519404:+@chr3:52519245:52519404:+.pdf': No such file or directory

It happened for all the entries in my event file, and I got to output sashimi plot. 
Looking into the folder I see indexing files, but no plots. What might be the issue here? I apologize I am not an expert bioinformatician so I cannot debugg it myself.

**Comment by EricKutschera** [comment]
This looks like the main error:
```
pickled_file = open(pickled_filename, 'wb')
IOError: [Errno 71] Protocol error: '/media/sf_H_DRIVE/rMats/Sashimi/SE_grouped_output/Sashimi_index_STAB1_329/chr3/chr3:52518723:52518869:+@chr3:52519185:52519404:+@chr3:52519245:52519404:+.pickle'
```

Are you able to manually create that directory (if it doesn't already exist) `/media/sf_H_DRIVE/rMats/Sashimi/SE_grouped_output/Sashimi_index_STAB1_329/chr3/` and then from the python interpreter run: `open('/media/sf_H_DRIVE/rMats/Sashimi/SE_grouped_output/Sashimi_index_STAB1_329/chr3/chr3:52518723:52518869:+@chr3:52519185:52519404:+@chr3:52519245:52519404:+.pickle', 'wb')`?

If that doesn't work, can you run `open('/media/sf_H_DRIVE/rMats/Sashimi/SE_grouped_output/Sashimi_index_STAB1_329/chr3/test_wb.txt', 'wb')` and `open('/media/sf_H_DRIVE/rMats/Sashimi/SE_grouped_output/Sashimi_index_STAB1_329/chr3/test_wt.txt', 'wt')`?

**Comment by sr8510** [comment]
This is happening with all the events in my eventfile, so I am guessing it might have to do with the file prefix [as in rMATs, where the usage of ":" causes issues]. I only posted the last error in a series of errors so my comment won't be pages long. can this be edited in rmats2sashimiplot code?

**Comment by sr8510** [comment]
So I went through the code of rmats2sashimiplot, and I changed all ":" to "_". This has solved part of the issue, as the indexing files for each gene were produced when I used an event file to generate sashimi plots for all genes using the grouping argument. However, I still do not get sashimi plots output. I got this output [sample of 1 gene output]: 

Through 0 genes...
Loaded 1 genes
  - Loading of genes from GFF took 0.00 seconds
Making directory: /home/user/Documents/rMats/Sashimi/A3SS/Sashimi_index_STAB1_329/chr3
  - Chromosome serialization took 0.00 seconds
Outputting gene records in GFF format...
  - Output file: /home/user/Documents/rMats/Sashimi/A3SS/Sashimi_index_STAB1_329/genes.gff
  - Serialization of genes from GFF took 0.00 seconds
Indexing of GFF took 0.00 seconds.
/home/user/anaconda3/envs/miso/bin/python /home/user/anaconda3/envs/miso/lib/python2.7/site-packages/MISO/misopy/sashimi_plot/sashimi_plot.py --plot-event "chr3_52518723_52518869_+@chr3_52519185_52519404_+@chr3_52519245_52519404_+" /home/user/Documents/rMats/Sashimi/A3SS/Sashimi_index_STAB1_329 /home/user/Documents/rMats/Sashimi/A3SS/Sashimi_index_STAB1_329/sashimi_plot_settings.txt --output-dir /home/user/Documents/rMats/Sashimi/A3SS/Sashimi_plot
/home/user/anaconda3/envs/miso/lib/python2.7/site-packages/matplotlib/cbook/deprecation.py:107: MatplotlibDeprecationWarning: The mpl_toolkits.axes_grid module was deprecated in version 2.1. Use mpl_toolkits.axes_grid1 and mpl_toolkits.axisartist provies the same functionality instead.
  warnings.warn(message, mplDeprecation, stacklevel=1)
Reading settings from: /home/user/Documents/rMats/Sashimi/A3SS/Sashimi_index_STAB1_329/sashimi_plot_settings.txt
Parsing data:bam_prefix
Parsing data:miso_prefix
Parsing data:bam_files
Parsing data:miso_files
Parsing plotting:group_info
Parsing plotting:font_size
Parsing plotting:reverse_minus
Parsing plotting:show_xlabel
Parsing plotting:nyticks
Parsing plotting:min_counts
Parsing plotting:text_background
Parsing plotting:logged
Parsing plotting:plot_label
Parsing plotting:show_ylabel
Parsing plotting:fig_height
Parsing plotting:nxticks
Parsing plotting:plot_title
Parsing plotting:exon_scale
Parsing plotting:fig_width
Parsing plotting:intron_scale
Parsing plotting:resolution
Parsing plotting:bar_posteriors
Parsing plotting:number_junctions
Parsing plotting:show_posteriors
Parsing plotting:colors
Parsing plotting:sample_labels
Reading dimensions from settings...
 - Height: 7.00
 - Width: 8.00
Plotting read densities and MISO estimates along event...
  - Event: chr3_52518723_52518869_+@chr3_52519185_52519404_+@chr3_52519245_52519404_+
Setting up plot using dimensions:  [8.0, 7.0]
Using intron scale  5.0
Using exon scale  1.0
Traceback (most recent call last):
  File "/home/user/anaconda3/envs/miso/lib/python2.7/site-packages/MISO/misopy/sashimi_plot/sashimi_plot.py", line 293, in <module>
    main()
  File "/home/user/anaconda3/envs/miso/lib/python2.7/site-packages/MISO/misopy/sashimi_plot/sashimi_plot.py", line 289, in main
    plot_label=plot_label)
  File "/home/user/anaconda3/envs/miso/lib/python2.7/site-packages/MISO/misopy/sashimi_plot/sashimi_plot.py", line 160, in plot_event
    plot_label=plot_label)
  File "/home/user/anaconda3/envs/miso/lib/python2.7/site-packages/MISO/misopy/sashimi_plot/plot_utils/plot_gene.py", line 838, in plot_density_from_file
    plot_title=plot_title)
  File "/home/user/anaconda3/envs/miso/lib/python2.7/site-packages/MISO/misopy/sashimi_plot/plot_utils/plot_gene.py", line 330, in plot_density
    group_files, group_labels, group_colors = analyze_group_info(group_info, bam_files, settings["sample_labels"])
  File "/home/user/anaconda3/envs/miso/lib/python2.7/site-packages/MISO/misopy/sashimi_plot/plot_utils/plot_gene.py", line 230, in analyze_group_info
    group_file = open(gf_path, 'r')
IOError: [Errno 2] No such file or directory: 'A3SS.gf'
mv: cannot stat '/home/user/Documents/rMats/Sashimi/A3SS/Sashimi_plot/chr3_52518723_52518869_+@chr3_52519185_52519404_+@chr3_52519245_52519404_+.pdf': No such file or directory

So I thing the problem now is that the file A3ss.gf does not exist for some reason. So why is in not generated? and how to fix this error?

**Comment by EricKutschera** [comment]
> So I went through the code of rmats2sashimiplot, and I changed all ":" to "_"

Can you make a pull request with that code change or list the files that you had to edit? That change will be useful for other users

For this error:
```
group_file = open(gf_path, 'r')
IOError: [Errno 2] No such file or directory: 'A3SS.gf'
```
It looks like it would happen if your command line had: `--group-info A3SS.gf`, but that file did not exist. The group info file is an optional argument that you can provide if you want to group multiple inputs into a single plot

**Comment by sr8510** [comment]
Hi, Thanks for that. Removing the argument --group-info fixed the issue. I get the sashimi plots with 1 plot per replicate, which can work. 

As for the code edit, I edited lines 486~523 in rmats2sashimiplot.py script. I changed every ":" to "_" to get output files without : in their names which caused the crash before.
