### ISSUE TITLE
Invalid Contig

### ISSUE THREAD

**Issue by atly2000** [Xinglab/rmats2sashimiplot#64]
`Error retrieving files from 6: invalid contig `6`
Are you sure 6 appears in your BAM file?
Aborting plot..`

I am using rmats2sashimiplot to plot one skipped exon event. 
The indexing worked, but I was not able to make any plots. 
I got this error, so I changed the value under "chr" in my event file from "6" to "chr6."
Even when I do this, I get the same issue. What should I do?

**Comment by EricKutschera** [comment]
rmats2sashimiplot tries to handle the case where the event file uses 'chr' for contigs and the bam file does not. Specifically it checks the first alignment in the bam to see if that contig starts with 'chr' and if it doesn't then rmats2sashimiplot removes the 'chr' prefix from the event file: https://github.com/Xinglab/rmats2sashimiplot/blob/v2.0.4/src/rmats2sashimiplot/rmats2sashimiplot.py#L523

You can check the unique contigs in your bam file with:
```
samtools view /path/to/file.bam | cut -f 3 | uniq
```

One possible explanation for your error is that your bam file uses chr6, but also has some other contig that doesn't start with chr. rmats2sashimiplot may decide to remove the 'chr' prefix from your event file (if it sees that non-chr contig first) which would cause that error regardless of whether you put chr6 or just 6 in your event file. You could filter your bam file down to just the target contig (chr6) to avoid that situation with:
```
samtools view -h /path/to/file.bam chr6 > /path/to/new_filtered_file.sam
samtools view -b /path/to/new_filtered_file.sam > /path/to/new_filtered_file.bam
```

**Comment by atly2000** [comment]
Thank you. I have checked the contigs and see that the bam file uses chr6 alongside other contig types. 
```
ERCC-00168
ERCC-00171
...

chr6
chr7
chr8
chr9
chrM
chrX
```
I tried the second method next to filter for only chr6 and got this error:
```
`samtools view -h ENCFF083YAC.bam chr6 > ENCFF083YAC.sam

[E::idx_find_and_load] Could not retrieve index file for 'ENCFF083YAC.bam'
[main_samview] random alignment retrieval only works for indexed BAM or CRAM files.`
```

How do I get an indexed file? I have the .bai files from an indexing I did previously.

**Comment by EricKutschera** [comment]
If you already have a .bai file for that bam then you can copy that .bai file to the same directory as the .bam file and samtools should detect it. Otherwise you can generate a new .bai file with:
```
samtools index ENCFF083YAC.bam
```

**Comment by atly2000** [comment]
It worked. Thank you very much.
If I wanted to filter my bam files for only chr+ number in the future, how would I do it?

**Comment by EricKutschera** [comment]
It looks like samtools supports filtering by a regular expression with `-e`. I think this should filter to only alignments with contig like `chr{digits}`:
`samtools view -h -e 'rname =~ "^chr[0123456789]+$"' {file.bam}`
If you want to include everything that starts with 'chr' then you could try `samtools view -h -e 'rname =~ "^chr"'`

I also made a code change that adds a new argument to rmats2sashimiplot (`--keep-event-chr-prefix`) that disables the editing of the input events file: https://github.com/Xinglab/rmats2sashimiplot/pull/67

I think if you run with the new code and `--keep-event-chr-prefix` then you should not see the error as long as you specify the contig name correctly in the events file, even if you do not filter your bam file
