### ISSUE TITLE
Using rmats2sashimiplot with just one group

### ISSUE THREAD

**Issue by jeneaadams** [Xinglab/rmats2sashimiplot#65]
It is possible to run the tool with just one group, but it still throws an error that `--l2` and `--b2 ` are required, when they do not need to be. 

![image](https://user-images.githubusercontent.com/54278292/124672930-e93c6c80-de85-11eb-8cf8-b8a56d1a0441.png)

Currently line 765 of the source codes states: 

```
required_group.add_argument("--l2", dest="l2", required=True,
                                help="The label for second sample.")
```

**Comment by EricKutschera** [comment]
I agree that rmats2sashimiplot unnecessarily requires `--l2` even when only `--b1` is given. Here's a code change to only require `--l1` if `--b1` or `--s1` is given, and similarly only require `--l2` if `--b2` or `--s2` is given: https://github.com/Xinglab/rmats2sashimiplot/pull/66

Did you also see an error where `--b2` was required? I think that should not happen after: https://github.com/Xinglab/rmats2sashimiplot/pull/42

**Comment by jeneaadams** [comment]
Got it. No, I didn't see an error for `--b2`.
