### ISSUE TITLE
Some sashimiplots are unlike the corresponding events found by rmats

### ISSUE THREAD

**Issue by redddlion** [Xinglab/rmats2sashimiplot#69]
Hi,
     I'm confused about some results of rmats2sashimiplot. Some sashimiplot plots of SE events, which were found by rMATS, look like A3SS or A5SS but not SE event. For example the scrrenshot, I don't find skipping in it 
![44faed09-817d-4fd1-8f1d-a698e2a2de85](https://user-images.githubusercontent.com/41217569/131765212-d9ab106d-5103-4aad-9277-b26da22b2eac.png)

**Comment by EricKutschera** [comment]
I agree that the plot looks like it is for an A3SS or A5SS event. What was the command line you used to generate that plot? If you used the `-e` argument can you share the first few lines from that file?
