### ISSUE TITLE
Error with running on MXE event types

### ISSUE THREAD

**Issue by bahramis** [Xinglab/rmats2sashimiplot#7]
It works great for four types of events (SE, A3SS, A5SS and RI)

but as soon as I change the event type to MXE, with the following command,

> rmats2sashimiplot --b1 exp_1.bam,exp_2.bam,exp_3.bam --b2 ctl_1.bam,ctl_2.bam,ctl_3.bam -t MXE -e MATS_output/MXE.MATS.JCEC.txt --l1 EXP --l2 CTL --exon_s 1 --intron_s 5 -o EXP_plots_MXE

It exits with this error:

'EventCoor' object has no attribute 'se_s'
There is an exception in plot_with_eventsfile

My guess is that since the file header for MXE is different than other type of AS events, it doesn't work for that event.

Please investigate.

**Comment by ShiehShieh** [comment]
We've fixed this bug. Will update it in next commit.

What's more, we notice that our previous version left the 'se_s' and 'se_e' be blank, which means the title of MXE sashimiplot will be something like 'chrx:2222:3333:-@chrx:::-@chrx:8888:9999:-'.
![image](https://cloud.githubusercontent.com/assets/6049252/23297677/584f077c-fab5-11e6-98dc-ac9bfbc7aa05.png)

Should we replace it by 'chrx:2222:3333:-@chrx:4444:5555:-@chrx:6666:7777:-@chrx:8888:9999:-'?, i.e. insert the first skipped exon and the second skipped exon into title.
![image](https://cloud.githubusercontent.com/assets/6049252/23297665/5108c822-fab5-11e6-9a09-0f5c5805c3f6.png)

**Comment by bahramis** [comment]
Yes I I think we should have both exon coordinates in the file name. It's useful to have all the information in the file name to point uniquely to an event.

**Comment by ShiehShieh** [comment]
Bug fixed.
