### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by OnkarMulay** [Xinglab/rmats2sashimiplot#71]
python /g/data/zq45/onkar/Shashimi/rmats2sashimiplot/src/rmats2sashimiplot/rmats2sashimiplot.py --b1 {bam files}, --b2 {bam files}, -t SE -e /g/data/zq45/onkar/Shashimi/SE.MATS.JC.txt --l1 Ovarian --l2 Benign --exon_s 1 --intron_s 3 -o /g/data/zq45/onkar/test_grouped_output --group-info grouping.gf

'bam1_1/Aligned.sortedByCoord.out.bam' is indexed already: 'bam1_1/Aligned.sortedByCoord.out.bam.bai'
'bam2_1/Aligned.sortedByCoord.out.bam' is indexed already: 'bam2_1/Aligned.sortedByCoord.out.bam.bai'

list index out of range
There is an exception in plot_with_eventsfile
Traceback (most recent call last):
  File "/g/data/zq45/onkar/Shashimi/rmats2sashimiplot/src/rmats2sashimiplot/rmats2sashimiplot.py", line 908, in <module>
    main()
  File "/g/data/zq45/onkar/Shashimi/rmats2sashimiplot/src/rmats2sashimiplot/rmats2sashimiplot.py", line 904, in main
    plot_with_eventsfile(options)
  File "/g/data/zq45/onkar/Shashimi/rmats2sashimiplot/src/rmats2sashimiplot/rmats2sashimiplot.py", line 585, in plot_with_eventsfile
    options.events_file = create_chr_aware_events_file(options)
  File "/g/data/zq45/onkar/Shashimi/rmats2sashimiplot/src/rmats2sashimiplot/rmats2sashimiplot.py", line 570, in create_chr_aware_events_file
    orig_chr_column = columns[chr_index]
IndexError: list index out of range

Can you help me with this?
Thanks

**Comment by EricKutschera** [comment]
That error is from this line of the code: https://github.com/Xinglab/rmats2sashimiplot/blob/fedd1bbe9eca37cee510393f294795eaa7e52eaf/src/rmats2sashimiplot/rmats2sashimiplot.py#L570

It is checking the file given on the command line as `-e /g/data/zq45/onkar/Shashimi/SE.MATS.JC.txt`. That file is expected to have a column with header `chr`, but based on the error message it seems that the file did not have that header

Can you share the first 2 lines of that file? Did that file come directly from rmats output or was it modified before running rmats2sashimiplot?

**Comment by OnkarMulay** [comment]
I tried and replaced file with direct rmats output file, but still same issues.
What should I do? Any suggestions?

Thanks

**Comment by OnkarMulay** [comment]
Ok, **can you share your email ID?**
I shall give you 4 bam files and the SE.MATS.JCEC.txt
I just can't release few things to the public.

And by the time I'll try debugging using print() statements and check where is error coming from

**Comment by EricKutschera** [comment]
kutscherae@chop.edu

**Comment by xiaonalu** [comment]
Hi, I encounter the same error, while I am using the coordinate input. Is there a way to correct the header? Thanks

**Comment by EricKutschera** [comment]
The stack trace from the original post in this issue is from `plot_with_eventsfile` (the `-e` parameter). If you got the same error message while using the coordinate input (`-c` parameter) then it could be for a different reason. Did you get a stack trace with the error message? What is the full command you ran?

**Comment by xiaonalu** [comment]
Hi, I got IndexError: list index out of range as below:
Indexing 'sashimi_trial.bam'.
list index out of range
There is an exception in plot_with_coordinate
Traceback (most recent call last):
  File "/rmats2/rmats2sashimiplot-master/src/rmats2sashimiplot/rmats2sashimiplot.py", line 908, in <module>
    main()
  File "/rmats2/rmats2sashimiplot-master/src/rmats2sashimiplot/rmats2sashimiplot.py", line 902, in main
    plot_with_coordinate(options)
  File "/rmats2/rmats2sashimiplot-master/src/rmats2sashimiplot/rmats2sashimiplot.py", line 383, in plot_with_coordinate
    in_strand = tmp_str[1]
IndexError: list index out of range

I ran it as
python /rmats2/rmats2sashimiplot-master/src/rmats2sashimiplot/rmats2sashimiplot.py -o trial -c /genome/gencode.vM27.annotation.gff3 --b1  sashimi_trial.bam --l1 trial

Thank you
________________________________

**Comment by EricKutschera** [comment]
That error happens because the -c parameter is expected to have the format `{chr}:{strand}:{start}:{end}:{gff3}` as in the example from the README: https://github.com/Xinglab/rmats2sashimiplot/tree/v2.0.4#bam-files-with-coordinate-and-annotation
`-c chr16:+:9000:25000:./rmats2sashimiplot_test_data/annotation.gff3`

The command you posted only has the gff3 part of the -c parameter

**Comment by xiaonalu** [comment]
Thank you!!!
I added the {chr}:{strand}:{start}:{end} before gff3, and the program did run a little. However, it stopped by another error, IndexError: tuple index out of range. Do you mind guiding me on it as well? Thank you so much

Setting up plot using dimensions:  [8.0, 7.0]
Using intron scale  1.0
Using exon scale  1.0
Reading sample label: trial-1
Traceback (most recent call last):
  File "/rmats2/rmats2sashimiplot-maste
r/src/MISO/misopy/sashimi_plot/sashimi_plot.py", line 293, in <module>
    main()
  File "/rmats2/rmats2sashimiplot-maste
r/src/MISO/misopy/sashimi_plot/sashimi_plot.py", line 285, in main
    plot_event(event_name, pickle_dir, settings_filename, output_dir,
  File "/rmats2/rmats2sashimiplot-maste
r/src/MISO/misopy/sashimi_plot/sashimi_plot.py", line 155, in plot_event
    plot_density_from_file(settings_filename, pickle_filename, event_name,
  File "/rmats2/rmats2sashimiplot-maste
r/src/MISO/misopy/sashimi_plot/plot_utils/plot_gene.py", line 837, in plot_den
sity_from_file
    plot_density(sashimi_obj, pickle_filename, event, group_info=group_info,
  File "/rmats2/rmats2sashimiplot-maste
r/src/MISO/misopy/sashimi_plot/plot_utils/plot_gene.py", line 382, in plot_den
sity
    plotted_ax, maxy = plot_density_single(settings, sample_label,
  File "/rmats2/rmats2sashimiplot-maste
r/src/MISO/misopy/sashimi_plot/plot_utils/plot_gene.py", line 86, in plot_dens
ity_single
    readsToWiggle_pysam(subset_reads, tx_start, tx_end, wiggle, jxns)
  File "/rmats2/rmats2sashimiplot-maste
r/src/MISO/misopy/sashimi_plot/plot_utils/plot_gene.py", line 542, in readsToW
iggle_pysam
    cigar_str = sam_utils.sam_cigar_to_str(read.cigar)
  File "/rmats2/rmats2sashimiplot-maste
r/src/MISO/misopy/sam_utils.py", line 309, in sam_cigar_to_str
    cigar_str += "%d%s" %(c[1], CIGAR_TYPES[c[0]])
IndexError: tuple index out of range

________________________________

**Comment by OnkarMulay** [comment]
This is because you are not loading samtools... module load samtools

Sent from Yahoo Mail on Android 
 
  On Tue, Dec 14, 2021 at 21:00, ***@***.***> wrote:   

Thank you!!!
I added the {chr}:{strand}:{start}:{end} before gff3, and the program did run a little. However, it stopped by another error, IndexError: tuple index out of range. Do you mind guiding me on it as well? Thank you so much

Setting up plot using dimensions: [8.0, 7.0]
Using intron scale 1.0
Using exon scale 1.0
Reading sample label: trial-1
Traceback (most recent call last):
 File "/rmats2/rmats2sashimiplot-maste
r/src/MISO/misopy/sashimi_plot/sashimi_plot.py", line 293, in <module>
 main()
 File "/rmats2/rmats2sashimiplot-maste
r/src/MISO/misopy/sashimi_plot/sashimi_plot.py", line 285, in main
 plot_event(event_name, pickle_dir, settings_filename, output_dir,
 File "/rmats2/rmats2sashimiplot-maste
r/src/MISO/misopy/sashimi_plot/sashimi_plot.py", line 155, in plot_event
 plot_density_from_file(settings_filename, pickle_filename, event_name,
 File "/rmats2/rmats2sashimiplot-maste
r/src/MISO/misopy/sashimi_plot/plot_utils/plot_gene.py", line 837, in plot_den
sity_from_file
 plot_density(sashimi_obj, pickle_filename, event, group_info=group_info,
 File "/rmats2/rmats2sashimiplot-maste
r/src/MISO/misopy/sashimi_plot/plot_utils/plot_gene.py", line 382, in plot_den
sity
 plotted_ax, maxy = plot_density_single(settings, sample_label,
 File "/rmats2/rmats2sashimiplot-maste
r/src/MISO/misopy/sashimi_plot/plot_utils/plot_gene.py", line 86, in plot_dens
ity_single
 readsToWiggle_pysam(subset_reads, tx_start, tx_end, wiggle, jxns)
 File "/rmats2/rmats2sashimiplot-maste
r/src/MISO/misopy/sashimi_plot/plot_utils/plot_gene.py", line 542, in readsToW
iggle_pysam
 cigar_str = sam_utils.sam_cigar_to_str(read.cigar)
 File "/rmats2/rmats2sashimiplot-maste
r/src/MISO/misopy/sam_utils.py", line 309, in sam_cigar_to_str
 cigar_str += "%d%s" %(c[1], CIGAR_TYPES[c[0]])
IndexError: tuple index out of range

________________________________

**Comment by xiaonalu** [comment]
Actually, I did load the Samtools. The version I am using is SAMtools/1.12-GCCcore-10.2.0. Is a particular version Sashimi like? Thanks
Best
Xiaona
________________________________

**Comment by EricKutschera** [comment]
I'm using samtools 1.12 and pysam 0.16.0.1. You could check your pysam version with:
```
python
>>> import pysam
>>> pysam.version.__version__
```

**Comment by xiaonalu** [comment]
Thank you. I am using the pysam 0.16.0.1 as well. Here are the modules I think involved in the program... Any of them are not right? Thanks


Pysam/0.16.0.1-GCCcore-10.2.0
matplotlib/3.3.4-foss-2020b
SAMtools/1.12-GCCcore-10.2.0
Python/3.8.6-GCCcore-10.2.0

________________________________

**Comment by OnkarMulay** [comment]
Hi,
use the following suggestions:

1) don't include string characters chr in start-stop coordinates... just use 9:12321-12313
if this doesn't work
2) share your header and first 3-4 lines of txt file which has events

**Comment by xiaonalu** [comment]
Hi,
Thanks for your suggestions. I tried to remove the chr, but still received the same error message. However, the program goes well when I use test data. I was wondering if I can send a few transcripts to your email to have your help looking at it? Thank you
Best
Xiaona
________________________________

**Comment by OnkarMulay** [comment]
Yes, I believe that the text file with events might have some issue....Before sending me just see if all column names are same with any reference txt ***@***.***

Sent from Yahoo Mail on Android 
 
  On Wed, Dec 15, 2021 at 9:18, ***@***.***> wrote:   

Hi,
Thanks for your suggestions. I tried to remove the chr, but still received the same error message. However, the program goes well when I use test data. I was wondering if I can send a few transcripts to your email to have your help looking at it? Thank you
Best
Xiaona
________________________________

**Comment by xiaonalu** [comment]
Hi, 

I think the problem starts from the genes.gff file, if it's the one generated before the event file. when using test data, the files reads as 

chr16	SE	gene	13501	21000	.	+	.	ID=chr16_13501_13700_+@chr16_18251_18350_+@chr16_20751_21000_+;Name=GENE_NAME_chr16_13501_13700_+@chr16_18251_18350_+@chr16_20751_21000_+

However, in my data file, it goes as 
chr16	SE	gene	13501	21000	.	+	.	ID=chr16_13501_13700_+;Name=GENE_NAME_chr16_13501_13700_+

the generated gff3 file also missed the @ part. I think this probably because of my input annotation gff3. I use the gencode.vM27.annotation.gff3. It does not have the @ part. Is it correct? 

I cannot see your email address, may due to some rules of the web? Thanks
Best
Xiaona
