### ISSUE TITLE
'chr' is not in list error

### ISSUE THREAD

**Issue by dhivyaa-6** [Xinglab/rmats2sashimiplot#72]
I used the recent version of rmats2sashimiplot (with the fix for chr names) but still get an error

     python $OUT/rmats2sashimiplot.py --b1 $DIR/3--1new.bam,$DIR/3--2new.bam,$DIR/3--3new.bam --b2 $DIR/4--1new.bam,$DIR/4--2new.bam,$DIR/4--3new.bam -t SE -e gene_SE.txt --l1 SampleOne --l2 SampleTwo --exon_s 1 --intron_s 5 -o test_org --group-info grouping.gf

###gene_SE.txt
            ID      GeneID  geneSymbol      chr     strand  exonStart_0base exonEnd upstreamES      upstreamEE downstreamES     downstreamEE    ID      IJC_SAMPLE_1    SJC_SAMPLE_1    IJC_SAMPLE_2    SJC_SAMPLE_2IncFormLen      SkipFormLen     PValue  FDR     IncLevel1       IncLevel2       IncLevelDifference
104617  "ENSG00000082516"       "GEM"        5       -       154904506       154904629       154903079   154903175       154905362       154905476       104617  172,159,156     1,0,0   113,155,134
0,0,2   271     149     1       1.0     0.99,1.0,1.0    1.0,1.0,0.974   0.005
104618  "ENSG00000082516"       "GEM"        5       -       154911726       154911898       154907590   154907818       154912898       154913038       104618  97,105,95       0,3,0   77,92,58   0,0,0    298     149     1       1.0     1.0,0.946,1.0   1.0,1.0,1.0     -0.018

##grouping.gf
     firstGroup: 1,2,3
     secondGroup: 4,5,6

ERROR
'chr' is not in list
There is an exception in plot_with_eventsfile

**Comment by dhivyaa-6** [comment]
I do not think it is the formatting issue, the stack trace looks like below:

'chr' is not in list
There is an exception in plot_with_eventsfile

**Comment by EricKutschera** [comment]
I'm not sure why the output does not include more details. When I run using the latest rmats2sashimiplot commit (https://github.com/Xinglab/rmats2sashimiplot/tree/fedd1bbe9eca37cee510393f294795eaa7e52eaf) and copy the contents of gene_SE.txt from your post, I get this stacktrace

```
'chr' is not in list
There is an exception in plot_with_eventsfile
Traceback (most recent call last):
  File "./src/rmats2sashimiplot/rmats2sashimiplot.py", line 908, in <module>
    main()
  File "./src/rmats2sashimiplot/rmats2sashimiplot.py", line 904, in main
    plot_with_eventsfile(options)
  File "./src/rmats2sashimiplot/rmats2sashimiplot.py", line 585, in plot_with_eventsfile
    options.events_file = create_chr_aware_events_file(options)
  File "./src/rmats2sashimiplot/rmats2sashimiplot.py", line 568, in create_chr_aware_events_file
    chr_index = columns.index('chr')
ValueError: 'chr' is not in list
```

You could try adding some print statements near that line to figure out what is happening

**Comment by woaisyr** [comment]
I had this problem too, and I think I've solved it.
I chose some results myself to show,but I forgot to add the colnames.Adding the colnames  might solve the problem.
