### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by wuzhigui** [Xinglab/rmats2sashimiplot#77]
Hello ~
![image](https://user-images.githubusercontent.com/70992194/160549389-45ab5689-4339-4a29-9ab5-1b74b2cea7a1.png)
My indexs have been done , but I dont't know why `IndexError: list index out of range` this error happened .
Well ,this is  the output of  rMATS.4.0.1.  Is anything wrong ?
![image](https://user-images.githubusercontent.com/70992194/160551622-563b722f-3d8a-445a-8d60-652dfbc53910.png)

**Comment by wuzhigui** [comment]
Yeah , that's really True !
I have found this !
But , the precious code may be have something wrong too .
` python2.7 /root/software/RNASeq-MATS.py  -b1  `cat b11.txt` -b2 `cat b22.txt` -gtf /root/software/gtf/hg38.knownGene.gtf -o out_test -t single -len 100 -a 8 -r1 72,75 -sd1 40,35 -r2 70,65 -sd2 48,45 8 -c 0.05 -analysis P -expressionChange 20`
I used this code  and I have no idea that why the output file need a config.txt ?
The software is MATS.3.0.5.beta.
Thanks!
![e3aaa4b823f935f554ee0a161ba799a](https://user-images.githubusercontent.com/70992194/160630915-594a9db6-b83f-4ab5-8aab-47bf3c24686c.png)

**Comment by EricKutschera** [comment]
That is an old version of mats (which I'm not familiar with). I recommend using the latest version of rmats if you can: https://github.com/Xinglab/rmats-turbo

I'm closing this issue since the error is not for rmats2sashimiplot

**Comment by wuzhigui** [comment]
Anyway ,thanks very much !
