### ISSUE TITLE
Program exits in certain cases

### ISSUE THREAD

**Issue by bahramis** [Xinglab/rmats2sashimiplot#8]
The rMATS output that creates the error is:

ID	GeneID	geneSymbol	chr	strand	exonStart_0base	exonEnd	upstreamES	upstreamEE	downstreamES	downstreamEE	ID	IJC_SAMPLE_1	SJC_SAMPLE_1	IJC_SAMPLE_2	SJC_SAMPLE_2	IncFormLen	SkipFormLen	PValue	FDR	IncLevel1	IncLevel2	IncLevelDifference
48181	"ENSG00000213468"	"RP11-453F18__B.1"	chrX	-	130929836	130930359	130928351	130928494	130938999	130939065	48181	35,55,21	3,5,5	62,78,61	2,2,1	672	149	0.00109497010323	0.0251135565548	0.721,0.709,0.482	0.873,0.896,0.931	-0.263

The error is:

'NoneType' object has no attribute 'split'
There is an exception in preparing coordinate setting file

The command line is: 

rmats2sashimiplot --b1 exp1.bam,exp2.bam,exp3.bam --b2 ctl1.bam,ctl2.bam,ctl3.bam -t SE -e SE.MATS.JCEC_top_err.txt --l1 DAZL --l2 control --exon_s 1 --intron_s 5 -o DAZL_plots_SE

**Comment by ShiehShieh** [comment]
If there are successive underscore in geneSymbol field, this error will happen.
It will be fixed in our next release.
