### ISSUE TITLE
sample_labels = NA

### ISSUE THREAD

**Issue by Squirrelity** [Xinglab/rmats2sashimiplot#84]
Thanks for your tools！
I used the recent version of rmats2sashimiplot and run it successfully.
But I am confused that there is "sample_labels = NA" in the sashimi_plot_settings.txt and therefore sashimi plot displays "NA".
The configs of the sashimi_plot_settings.txt are as follows:
sample_labels = ["NA l1-1 IncLevel: 1.00","NA l1-2 IncLevel: 0.80","NA l2-1 IncLevel: 0.77","NA l2-2 IncLevel: 0.94"]
My codes are as follows:
rmats2sashimiplot \
--b1 b1_1.bam,b1_2bam \
--b2 b2_1.bam,b2_2.bam \
--l1 l1 \
--l2 l2 \
--exon_s 1 \
--intron_s 5 \
--min-counts 0 \
-t SE \
-e SE.MATS.JC.txt \
-o output \
-c mm10_ucsc.gtf
Thanks for your reply.

**Comment by EricKutschera** [comment]
The NA part of sample_labels in your output is in the location where the gene name should be. rmats2sashimiplot gets the gene name directly from the file given as `-e` (in your case `-e SE.MATS.JC.txt`):
https://github.com/Xinglab/rmats2sashimiplot/blob/v2.0.4/src/rmats2sashimiplot/rmats2sashimiplot.py#L577
https://github.com/Xinglab/rmats2sashimiplot/blob/v2.0.4/src/rmats2sashimiplot/rmats2sashimiplot.py#L225

**Comment by Squirrelity** [comment]
> The NA part of sample_labels in your output is in the location where the gene name should be. rmats2sashimiplot gets the gene name directly from the file given as `-e` (in your case `-e SE.MATS.JC.txt`): https://github.com/Xinglab/rmats2sashimiplot/blob/v2.0.4/src/rmats2sashimiplot/rmats2sashimiplot.py#L577 https://github.com/Xinglab/rmats2sashimiplot/blob/v2.0.4/src/rmats2sashimiplot/rmats2sashimiplot.py#L225

That's very helpful! Thanks for your help!
