### ISSUE TITLE
low quantity of fpkm in sashimi plot

### ISSUE THREAD

**Issue by ElenaSLuis** [Xinglab/rmats2sashimiplot#85]
Hey! I have a problem with the low quantity of fpkm that is reflected in the slashimi plot, but this result is not reflected in the output of the bams. I don't understand what is happening.

#convert my fastqc data to bams. 
conda activate ./conda_env

python rmats.py --s1 /data/elenasl/RNAseq_TLR4_TLR3/RNAseq_Pamplona/rmats_turbo_v4_1_2/s1.txt --s2 /data/elenasl/RNAseq_TLR4_TLR3/RNAseq_Pamplona/rmats_turbo_v4_1_2/s2.txt --gtf /data/elenasl/RNAseq_TLR4_TLR3/star/Homo_sapiens.GRCh38.79.gtf --bi /data/elenasl/RNAseq_TLR4_TLR3/star/ -t paired --readLength 59 --nthread 12 --od /data/elenasl/RNAseq_TLR4_TLR3/RNAseq_Pamplona/Resultados_Def_rmats/outputs_6h –tmp /data/elenasl/RNAseq_TLR4_TLR3/RNAseq_Pamplona/Resultados_Def_rmats/tmp_outputs_6h_final

#Download gffread to convert gtf data to gff
cd /data/elenasl/RNAseq_TLR4_TLR3/RNAseq_Pamplona/rmats_turbo_v4_1_2/gffread/
./gffread --keep-genes /data/elenasl/RNAseq_TLR4_TLR3/star/Homo_sapiens.GRCh38.79.gtf -o /data/elenasl/RNAseq_TLR4_TLR3/RNAseq_Pamplona/rmats_turbo_v4_1_2/gffread/some_file.gff3

#Then I run rmatsashimiplot
rmats2sashimiplot --b1 /data/elenasl/RNAseq_TLR4_TLR3/RNAseq_Pamplona/Resultados_Def_rmats/tmp_outputs_6h/2022-09-20-10_29_36_374303_bam1_1/Aligned.sortedByCoord.out.bam,\
/data/elenasl/RNAseq_TLR4_TLR3/RNAseq_Pamplona/Resultados_Def_rmats/tmp_outputs_6h/2022-09-20-10_29_36_374303_bam1_2/Aligned.sortedByCoord.out.bam,\
/data/elenasl/RNAseq_TLR4_TLR3/RNAseq_Pamplona/Resultados_Def_rmats/tmp_outputs_6h/2022-09-20-10_29_36_374303_bam1_3/Aligned.sortedByCoord.out.bam\
 --b2 /data/elenasl/RNAseq_TLR4_TLR3/RNAseq_Pamplona/Resultados_Def_rmats/tmp_outputs_6h/2022-09-20-10_29_36_374303_bam2_1/Aligned.sortedByCoord.out.bam,\
/data/elenasl/RNAseq_TLR4_TLR3/RNAseq_Pamplona/Resultados_Def_rmats/tmp_outputs_6h/2022-09-20-10_29_36_374303_bam2_2/Aligned.sortedByCoord.out.bam,\
/data/elenasl/RNAseq_TLR4_TLR3/RNAseq_Pamplona/Resultados_Def_rmats/tmp_outputs_6h/2022-09-20-10_29_36_374303_bam2_3/Aligned.sortedByCoord.out.bam\ -c 10:+:69895549:69902856:/data/elenasl/RNAseq_TLR4_TLR3/RNAseq_Pamplona/rmats_turbo_v4_1_2/gffread/some_file.gff3 --l1 CTL --l2 polyI:C_6h --exon_s 1 --intron_s 5\ -o /data/elenasl/RNAseq_TLR4_TLR3/RNAseq_Pamplona/Spliced_Genes/6hvsCTL/COL13A1

Example of the outputs of bam:
/data/elenasl/RNAseq_TLR4_TLR3/RNAseq_Pamplona/Resultados_Def_rmats/tmp_outputs_6h/2022-09-20-10_29_36_374303_bam1_1/Aligned.sortedByCoord.out.bam
USED: 85722153
NOT_PAIRED: 0
NOT_NH_1: 10683148
NOT_EXPECTED_CIGAR: 413388
NOT_EXPECTED_READ_LENGTH: 0
NOT_EXPECTED_STRAND: 0
EXON_NOT_MATCHED_TO_ANNOTATION: 3604030
JUNCTION_NOT_MATCHED_TO_ANNOTATION: 43723
CLIPPED: 0
TOTAL_FOR_BAM: 100466442

thank you in advance and I look forward to your answer.

Best regards,

Elena

**Comment by EricKutschera** [comment]
The commands you posted seem fine. The fpkm shown in the sashimiplot is calculated here: https://github.com/Xinglab/rmats2sashimiplot/blob/v2.0.4/src/MISO/misopy/sashimi_plot/plot_utils/plot_gene.py#L88

If the fpkm is low then the `wiggle` value is relatively low compared to the number of reads in your bam files. The code for counting the reads doesn't use reads with insertions or deletions: https://github.com/Xinglab/rmats2sashimiplot/blob/v2.0.4/src/MISO/misopy/sashimi_plot/plot_utils/plot_gene.py#L549

Can you check your bam files to see how many reads are in the region being plotted and how many of those reads have insertions or deletions? With the total reads in the bam files you should be able to roughly reproduce the calculation for the plot

Here's a related post: https://github.com/Xinglab/rmats2sashimiplot/issues/49#issuecomment-738877722

**Comment by ElenaSLuis** [comment]
hey! Thank you to answer me. 
I check the region read in the bam file:
 bedtools coverage -a /data/elenasl/RNAseq_TLR4_TLR3/RNAseq_Pamplona/Spliced_Genes/6hvsCTL/COL13A1/regions.bed -b /data/elenasl/RNAseq_TLR4_TLR3/RNAseq_Pamplona/Resultados_Def_rmats/tmp_outputs_6h/2022-09-20-10_29_36_374303_bam1_1/Aligned.sortedByCoord.out.bam
10      69895549        69902855        +       180     7306    7306    1.0000000

My regions.bed contain: 10    +    69895549        69902856
The position that I am using are : upstreamES and downstreamEE

It seems that the depth is well, so I don't understand where is the fail point.

**Comment by EricKutschera** [comment]
The rmats output has: `TOTAL_FOR_BAM: 100466442`
The bedtools coverage command shows 180 reads in that region
The rmats command had `--readLength 59`

The calculation for rpkm used by rmats2sashimiplot is:
`1e3 * (read_count/read_length) / (total_read_count / 1e6)`

If all 180 reads overlapped at a single position the value would be:
`1e3 * (180/59) / (100466442 / 1e6) = 30.37`

A single read would contribute about 0.17 to each position
