### ISSUE TITLE
rmats2sashimiplot error: local variable 'warning_flag' referenced before assignment There is an exception in preparing coordinate setting file

### ISSUE THREAD

**Issue by jamespblloyd** [Xinglab/rmats2sashimiplot#9]
Hello, I was very excited to try out rmats2sashimiplot but when I tried to run it on my own data and with the test data, I get the same warning and no Sashimi_plot directory. 
 
My command and the error is (I am running it in the same directory as the bam and gff3 files):
rmats2sashimiplot --b1 S1.R1.test.bam,S1.R2.test.bam,S1.R3.test.bam --b2 S2.R1.test.bam,S2.R2.test.bam,S2.R3.test.bam -c chr2:+:10090000:10110000:ensGene.gff3 --l1 PC3E --l2 GS689 --exon_s 1 --intron_s 5 -o test_coordinate_output
 
 
local variable 'warning_flag' referenced before assignment
There is an exception in preparing coordinate setting file
 ls test_coordinate_output/
Sashimi_index
jamesl@atomic:/data/jamesl/NMD/AS_NMD_SFs/SRSF126_KD_CHX/rmats2sashimiplot/testData$ ls test_coordinate_output/Sashimi_index/
sashimi_plot_settings.txt  SE.event.list.txt  tmp.gff3
 
I am not sure where the problem is coming from or why. I get the same problem when I run it on my (sorted) own bam files. I am running it on python2.7 with a Ubuntu 12.04 OS and I have /lab/64/app/samtools/samtools-0.1.16/ in my PATH variable. Could my samtools be an old version? 
 
Many thanks,
James

**Comment by ShiehShieh** [comment]
This error could happen when user inputs coordinates. It has been fixed in latest commit, please try it again.
