### ISSUE TITLE
Data type error of --min-counts

### ISSUE THREAD

**Issue by wu116** [Xinglab/rmats2sashimiplot#91]
Hello dear developer! 

I try to draw a picture with arg `--min-counts`, but I get an error like:
```
File "/home/x/miniconda3/envs/rmats/lib/python3.10/site-packages/rmats2sashimiplot-2.0.4-py3.10.egg/rmats2sashimiplot/rmats2sashimiplot.py", line 183, in conf_setting_file
    setting["min_counts"] = max(options.min_counts, 0)
TypeError: '>' not supported between instances of 'int' and 'str'
```
So I take a view of the code:
https://github.com/Xinglab/rmats2sashimiplot/blob/3160ef44c1b0587bce32876b36de24c0bc663c9f/src/rmats2sashimiplot/rmats2sashimiplot.py#L225
I think the program may read the `--min-counts` as a str instead of int, so I edit this line to:
```
setting["min_counts"] = max(int(options.min_counts), 0) 
```
And it works now.

**Comment by EricKutschera** [comment]
Thanks for reporting this. I merged a code change to address the issue
