### ISSUE TITLE
after running,no plot file

### ISSUE THREAD

**Issue by 44314474** [Xinglab/rmats2sashimiplot#94]
Hi!
When i run rmats2sashimiplot,there is no plot file.
I checked the running log,there are many error,but i have no idea,and i searched it by internet but there is no any ways .![image](https://user-images.githubusercontent.com/120501819/231926543-29f28ecb-a316-4a27-bcfb-72d1623dec99.png)
My command is :rmats2sashimiplot --b1 /public/home/wml/DGAT/08.gene_expression/xiaolongxia/03.bidui/bam/M_1.sort.bam,/public/home/wml/DGAT/08.gene_expression/xiaolongxia/03.bidui/bam/M_2.sort.bam,/public/home/wml/DGAT/08.gene_expression/xiaolongxia/03.bidui/bam/M_3.sort.bam --b2 /public/home/wml/DGAT/08.gene_expression/xiaolongxia/03.bidui/bam/NM_1.sort.bam,/public/home/wml/DGAT/08.gene_expression/xiaolongxia/03.bidui/bam/NM_2.sort.bam,/public/home/wml/DGAT/08.gene_expression/xiaolongxia/03.bidui/bam/NM_3.sort.bam -t MXE -e MXE.MATS.JC.txt --l1 M --l2 NM -o out3

Of course ,i run the sofeware by the test data,However,there also occured error.
![image](https://user-images.githubusercontent.com/120501819/231926836-0da34c1b-1434-4c7a-ae03-12ee3035862d.png)
I would appreciate it if you could give me any advice.
Thanks!

**Comment by EricKutschera** [comment]
mpl_toolkits.axes_grid was deprecated and eventually removed from newer versions of matplotlib. You should be able to use rmats2sashimiplot with matplotlib 3.4.3 or older

Here's a related post: https://groups.google.com/g/rmats-user-group/c/-Cf4K7Y1rIw/m/1zuhWWkLAgAJ

**Comment by EricKutschera** [comment]
rmats2sashimiplot v3.0.0 stops using that deprecated import
