### ISSUE TITLE
error while running on test data

### ISSUE THREAD

**Issue by rezarahman12** [Xinglab/rmats2sashimiplot#95]
Hi rmats2shashimiplot team,

I'm trying to run this software in test data. Below is my script-
my script-
cd $SLURM_SUBMIT_DIR
module load python
module load pysam
module load cmake/3.20.1-gcccore-10.3.0
module load samtools/1.13-gcc-10.3.0

#export PATH=/home/s4613408/sratoolkit.3.0.1-ubuntu64/bin:$PATH

python ./rmats2sashimiplot.py \
--b1 data/scratch/project_mnt/S0077/rmats_shashimiplot/sample_1_replicate_1.bam,/scratch/project_mnt/S0077/rmats_shashimiplot/sample_1_replicate_2.bam,/scratch/project_mnt/S0077/rmats_shashimiplot/sample_1_replicate_3.bam \
--b2 /scratch/project_mnt/S0077/rmats_shashimiplot/sample_2_replicate_1.bam,/scratch/project_mnt/S0077/rmats_shashimiplot/sample_2_replicate_2.bam,/scratch/project_mnt/S0077/rmats_shashimiplot/sample_2_replicate_3.bam \
--event-type SE -e /scratch/project_mnt/S0077/rmats_shashimiplot/SE.MATS.JC.txt \
--l1 SampleOne --l2 SampleTwo --exon_s 1 --intron_s 5 -o out

However, I'm encountering the below error-

[W::hts_idx_load3] The index file is older than the data file: /scratch/project_mnt/S0077/rmats_shashimiplot/sample_1_replicate_1.bam.bai
/sw/auto/rocky8.6/epyc3/software/Python/3.10.4-GCCcore-11.3.0/bin/python: can't open file '/scratch/project_mnt/S0077/MISO/misopy/index_gff.py': [Errno 2] No such file or directory
/sw/auto/rocky8.6/epyc3/software/Python/3.10.4-GCCcore-11.3.0/bin/python: can't open file '/scratch/project_mnt/S0077/MISO/misopy/sashimi_plot/sashimi_plot.py': [Errno 2] No such file or directory
mv: cannot stat '/scratch/project_mnt/S0077/rmats_shashimiplot/out/Sashimi_plot/chr16_13501_13700_+@chr16_18251_18350_+@chr16_20751_21000_+.pdf': No such file or directory

Could you please tell me what to need to overcome this error?
I appreciate your time and help.

Kind regards
Reza

**Comment by EricKutschera** [comment]
The main error is: `can't open file '/scratch/project_mnt/S0077/MISO/misopy/index_gff.py': [Errno 2] No such file or directory`

Here's the code that sets the path to that file: https://github.com/Xinglab/rmats2sashimiplot/blob/v2.0.4/src/rmats2sashimiplot/rmats2sashimiplot.py#L321

It's looking for index_gff.py relative to rmats2sashimiplot.py. It seems that somehow the file structure is not as expected. You could try downloading a new copy of the source code to a new directory

**Comment by rezarahman12** [comment]
Thank you so much for your quick reply. I've downloaded the new copy of rmats2sashimiplot.py into a new directory. However, it comes with error while running. please see below for your kind consideration.
The following have been reloaded with a version change:
  1) binutils/.2.36.1-gcccore-10.3.0 => binutils/.2.38-gcccore-11.3.0
  2) bzip2/.1.0.8-gcccore-10.3.0 => bzip2/.1.0.8-gcccore-11.3.0
  3) gcccore/.10.3.0 => gcccore/.11.3.0
  4) ncurses/.6.2-gcccore-10.3.0 => ncurses/.6.3-gcccore-11.3.0
  5) xz/.5.2.5-gcccore-10.3.0 => xz/.5.2.5-gcccore-11.3.0
  6) zlib/.1.2.11-gcccore-10.3.0 => zlib/.1.2.12-gcccore-11.3.0


The following have been reloaded with a version change:
  1) curl/.7.76.0-gcccore-10.3.0 => curl/.7.83.0-gcccore-11.3.0
  2) gcc/10.3.0 => gcc/11.3.0


The following have been reloaded with a version change:
  1) bzip2/.1.0.8-gcccore-11.3.0 => bzip2/.1.0.8-gcccore-10.3.0
  2) curl/.7.83.0-gcccore-11.3.0 => curl/.7.76.0-gcccore-10.3.0
  3) gcccore/.11.3.0 => gcccore/.10.3.0
  4) ncurses/.6.3-gcccore-11.3.0 => ncurses/.6.2-gcccore-10.3.0
  5) zlib/.1.2.12-gcccore-11.3.0 => zlib/.1.2.11-gcccore-10.3.0


The following have been reloaded with a version change:
  1) binutils/.2.38-gcccore-11.3.0 => binutils/.2.36.1-gcccore-10.3.0
  2) gcc/11.3.0 => gcc/10.3.0
  3) xz/.5.2.5-gcccore-11.3.0 => xz/.5.2.5-gcccore-10.3.0

  File "/scratch/project_mnt/S0077/rmats2shashimiplot/rmats2sashimiplot.py", line 72
    <title>rmats2sashimiplot/rmats2sashimiplot.py at master Â· Xinglab/rmats2sashimiplot Â· GitHub</title>
                                                            ^
SyntaxError: invalid character 'Â·' (U+00B7)

I appreciate your time and help.

Best regards
Reza

**Comment by EricKutschera** [comment]
The error is showing an html tag (`<title>`). I think you downloaded the html of the github page
```
File "/scratch/project_mnt/S0077/rmats2shashimiplot/rmats2sashimiplot.py", line 72
<title>rmats2sashimiplot/rmats2sashimiplot.py at master Â· Xinglab/rmats2sashimiplot Â· GitHub</title>
^
SyntaxError: invalid character 'Â·' (U+00B7)
```

Try getting a new copy of all of the rmats2sashimplot source files with: `git clone https://github.com/Xinglab/rmats2sashimiplot.git`

**Comment by rezarahman12** [comment]
Thanks a lot, Eric @EricKutschera.
Sorry for my mistake. Now, I've cloned as you suggested. I ran the job it has created the out folder, however, I'm getting the error follows-
The following have been reloaded with a version change:
  1) bzip2/.1.0.8-gcccore-11.3.0 => bzip2/.1.0.8-gcccore-10.3.0
  2) curl/.7.83.0-gcccore-11.3.0 => curl/.7.76.0-gcccore-10.3.0
  3) gcccore/.11.3.0 => gcccore/.10.3.0
  4) ncurses/.6.3-gcccore-11.3.0 => ncurses/.6.2-gcccore-10.3.0
  5) xz/.5.2.5-gcccore-11.3.0 => xz/.5.2.5-gcccore-10.3.0
  6) zlib/.1.2.12-gcccore-11.3.0 => zlib/.1.2.11-gcccore-10.3.0


The following have been reloaded with a version change:
  1) binutils/.2.38-gcccore-11.3.0 => binutils/.2.36.1-gcccore-10.3.0
  2) gcc/11.3.0 => gcc/10.3.0

[W::hts_idx_load3] The index file is older than the data file: /scratch/project_mnt/S0077/rmats_shashimiplot/sample_1_replicate_1.bam.bai
  File "/scratch/project_mnt/S0077/rmats2shashimiplot/rmats2sashimiplot/src/MISO/misopy/index_gff.py", line 77
    print "Making directory: %s" %(chrom_dir)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(...)?
  File "/scratch/project_mnt/S0077/rmats2shashimiplot/rmats2sashimiplot/src/MISO/misopy/sashimi_plot/sashimi_plot.py", line 46
    print "WARNING: %s does not end in .miso_bf, are you sure it is the " \
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(...)?
mv: cannot stat '/scratch/project_mnt/S0077/rmats2shashimiplot/out/Sashimi_plot/chr16_13501_13700_+@chr16_18251_18350_+@chr16_20751_21000_+.pdf': No such file or directory

I really appreciate your time and help. Could you please advise me on how to get rid of this error?

Best regards
Reza

**Comment by EricKutschera** [comment]
The code is written for Python2. You can either run it with Python2 or convert it to Python3 with https://github.com/Xinglab/rmats2sashimiplot/blob/v2.0.4/2to3.sh

Here is a similar post: https://github.com/Xinglab/rmats2sashimiplot/issues/83

**Comment by EricKutschera** [comment]
It looks like this is the line causing the error: https://github.com/Xinglab/rmats2sashimiplot/blob/v2.0.4/src/MISO/misopy/sashimi_plot/plot_utils/plot_gene.py#L75

It's trying to run samtools. I think the `OSError: [Errno 2] No such file or directory` is saying it could not find the samtools executable on your PATH. Do you have samtools installed?

**Comment by rezarahman12** [comment]
thanks a lot, Eric for your quick reply. I loaded the modules for samtools and bedtools, and now it worked. Thank you again for your kind help and suggestion.
