### ISSUE TITLE
How to understand the content in plot of  rmats2sashimiplot?

### ISSUE THREAD

**Issue by CarrieBishop** [Xinglab/rmats2sashimiplot#99]
Thanks for you developing the rmats2sashimiplot, which is very useful. I ran the rmats2sashimiplot successfully and got the plot. But I still have some problems of the content. 
1.Can you tell me how  to understand the content in plot? Such as what's the meaning of RPKM?What's the meaning of number in the middle of curve?
2.I have 5 repeat group in sample_1 and sample_2. Why the number in the middle of curve are differnent in the repeat group?
3.What's the IncLevel difference between the two samples can I think that they have significant differences?
4.There are some nan labels in some plot'IncLevel. How can I correct it?
Thanks for your reply.
<img width="274" alt="8a8491f73533f297cc144f9a038382a" src="https://github.com/Xinglab/rmats2sashimiplot/assets/133024702/f771dba1-8b74-4ed2-8ebc-9c38d57fc6af">
<img width="266" alt="78dc48cf26bb23419c0c10c536a550d" src="https://github.com/Xinglab/rmats2sashimiplot/assets/133024702/102c0a21-e9fe-4c49-9180-ed7df79e0b96">

**Comment by macoreL** [comment]
Hello. I have the problem like that "4.There are some nan labels in some plot'IncLevel ?". All IncLevel in the plot is nan. 
![image](https://github.com/Xinglab/rmats2sashimiplot/assets/40660066/cf8b753a-c63d-4e19-86f3-5d5c3f194b21)
IncLevel in input file is as following:
![image](https://github.com/Xinglab/rmats2sashimiplot/assets/40660066/f31b6597-d683-4a52-82d6-ce0eda701517)
do you konw why this happens? Thanks

**Comment by EricKutschera** [comment]
Here is the code that writes the IncLevel label: https://github.com/Xinglab/rmats2sashimiplot/blob/b1d6835e60f158a8717504794ab3e66220488337/src/rmats2sashimiplot/rmats2sashimiplot.py#L265

It should only give nan if it can't parse the IncLevel1 and IncLevel2 columns from your input file. That would happen if there were no counts for the event and NA in the rmats output file. The values in the spreadsheet screenshot look fine (not NA), but maybe there is some other issue with your input file. You could try adding print statements to that part of the code to see what value it is converting to nan

**Comment by macoreL** [comment]
Thanks for your reply. I got the reason why IncLevel displayed NA in the plot. The IncLevel value in the txt file generated by rMATS were changed into string after edited in excel. The  IncLevel displayed correctly when the value was set as number.
